version: '3.8'

services:
  biason-frontend:
    build:
      context: ./app/biason-frontend
    container_name: biason-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
