import { Book, CharityCampaign, GuestbookEntry } from './types';

export const INITIAL_CAMPAIGN: CharityCampaign = {
  campaign_name: 'Bìa Sờn Nắng Mới — Tri Ân Thương Binh Liệt Sĩ',
  beneficiary_name: 'Trung tâm Điều dưỡng Thương binh và Người có công Long Đất',
  beneficiary_address: 'Thị trấn Long Hải, huyện Long Điền, tỉnh Bà Rịa – Vũng Tàu',
  target_amount: 2000000,
};

export const INITIAL_BOOKS: Book[] = [
  {
    id: 1,
    qr_code: 'BSNM-001',
    title: 'Dì Hulia Và Nhà Văn Quèn',
    author: 'Mariô Vargax Lôxa (Mario Vargas Llosa)',
    publish_year: 1986,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Văn Học Dịch Thời Bao Cấp',
    price: 35000,
    condition_note: 'Bìa sờn mép nguyên bản, giấy bãi bằng ngả vàng thời kỳ 1986, gáy vững',
    summary: 'Kiệt tác hài hước tự truyện của đại văn hào giải Nobel Mario Vargas Llosa. Tác phẩm đan xen giữa mối tình sóng gió của chàng thanh niên Mario 18 tuổi với người dì họ Hulia, và những câu chuyện kịch truyền thanh kỳ lạ, đầy châm biếm sâu sắc của nhà biên kịch Pedro Camacho.',
    quote: 'Tình yêu và văn chương là hai điều cám dỗ lớn nhất của cuộc đời, khiến con người ta dám vượt qua mọi định kiến.',
    cover_image_url: '/book-di-julia.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 2,
    qr_code: 'BSNM-002',
    title: '40 Năm Văn Học (Tiểu Luận Phê Bình)',
    author: 'Nhiều tác giả (Bành Bảo, Hoàng Trung Thông, Hà Minh Đức...)',
    publish_year: 1986,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Lý Luận Phê Bình Văn Học',
    price: 35000,
    condition_note: 'Ấn bản kỷ niệm 40 năm văn học cách mạng (1945-1985), bìa sờn nhuộm màu thời gian, ruột nguyên vẹn',
    summary: 'Công trình tuyển tập tiểu luận phê bình đồ sộ tổng kết 40 năm chặng đường văn học cách mạng Việt Nam (1945 - 1985). Cuốn sách ghi lại những đánh giá cốt lõi về các tác phẩm đỉnh cao thời kỳ chống Pháp, chống Mỹ và những trăn trở đổi mới đầu tiên.',
    quote: 'Bốn mươi năm văn học là bốn mươi năm đồng hành cùng máu lửa non sông, nâng niu tâm hồn người chiến sĩ.',
    cover_image_url: '/book-40-nam-van-hoc.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 3,
    qr_code: 'BSNM-003',
    title: 'Kết Cục',
    author: 'Bô-rít Pô-lê-vôi (Boris Polevoy)',
    publish_year: 1985,
    publisher: 'NXB Quân Đội Nhân Dân',
    category: 'Ký Sự Chiến Tranh & Công Lý',
    price: 30000,
    condition_note: 'Bìa sờn mộc mạc, giấy in thời bao cấp nguyên vẹn chữ in typo của NXB Quân Đội Nhân Dân',
    summary: 'Tác phẩm lịch sử chấn động của nhà văn chiến sĩ Xô Viết Boris Polevoy, tường thuật lại toàn bộ quá trình Tòa án Quân sự Quốc tế Nuremberg xét xử tội phạm chiến tranh phát xít. Tác phẩm khẳng định công lý tất thắng của nhân loại tiến bộ trước bạo tàn.',
    quote: 'Tội ác chống lại loài người không bao giờ có thể bị lãng quên hay tha thứ trước tòa án lương tri.',
    cover_image_url: '/book-ket-cuc.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 4,
    qr_code: 'BSNM-004',
    title: 'Tìm Trầm',
    author: 'Minh Kiên',
    publish_year: 1987,
    publisher: 'NXB Văn Nghệ TP. Hồ Chí Minh',
    category: 'Tiểu Thuyết Đời Sống & Rừng Núi',
    price: 30000,
    condition_note: 'Ấn bản 1987, bìa nghệ thuật đồ họa thập niên 80 sờn nhẹ mép sách, các trang nguyên vẹn',
    summary: 'Tiểu thuyết khắc họa hành trình gian lao, sinh tử của những người phu trầm lặn lội giữa chốn rừng sâu núi thẳm miền Trung sau ngày giải phóng. Cuộc kiếm tìm kỳ nam quý giá đan xen với việc đi tìm chính nhân cách và giá trị lương thiện của con người giữa thử thách nghiệt ngã.',
    quote: 'Trầm hương sinh ra từ vết thương của cây dó bầu; đời người muốn tỏa hương cũng phải đi qua bao thăng trầm thử thách.',
    cover_image_url: '/book-tim-tram.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 5,
    qr_code: 'BSNM-005',
    title: 'Nắng Mới Trên Đỉnh Ăng-co',
    author: 'Hoàng Huân, Văn Lê, Đỗ Quảng, Nguyễn Việt Sơn, Nguyễn Khắc Viện',
    publish_year: 1981,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Ký Sự Tình Nghĩa Quốc Tế',
    price: 30000,
    condition_note: 'Bìa màu đất nguyên bản năm 1981, khắc họa bức phù điêu Angkor, gáy sờn cổ kính',
    summary: 'Tập ký sự chân thực và xúc động viết tại chiến trường Campuchia sau khi chế độ diệt chủng Khmer Đỏ bị lật đổ. Các tác giả ghi lại bước chân nghĩa tình của bộ đội tình nguyện Việt Nam giúp nhân dân bạn hồi sinh từ cõi chết, làm bừng sáng lại ánh nắng trên kỳ quan Angkor kỳ vĩ.',
    quote: 'Tia nắng mới rọi trên đỉnh tháp cổ không chỉ báo hiệu một ngày mới, mà là sự hồi sinh của cả một dân tộc được cứu thoát khỏi diệt chủng.',
    cover_image_url: '/book-nang-moi-ang-co.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 6,
    qr_code: 'BSNM-006',
    title: 'Thành Phố Hồ Chí Minh 10 Năm',
    author: 'Nguyễn Văn Linh',
    publish_year: 1985,
    publisher: 'NXB Sự Thật Hà Nội',
    category: 'Chính Trị & Xây Dựng Đất Nước',
    price: 30000,
    condition_note: 'Ấn bản gốc NXB Sự Thật 1985, bìa đỏ cờ cách mạng sờn nhẹ mép, ruột nguyên vẹn',
    summary: 'Tác phẩm chính trị quan trọng tổng kết 10 năm xây dựng Thành phố Hồ Chí Minh sau ngày giải phóng (1975-1985). Sách phân tích các thành tựu, thách thức và bài học kinh nghiệm trong quá trình cải tạo và phát triển thành phố.',
    quote: 'Mười năm xây dựng là mười năm cả thành phố cùng đồng lòng, biến hoang tàn thành hoa trái cho thế hệ mai sau.',
    cover_image_url: '/book-hcm-10-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 7,
    qr_code: 'BSNM-007',
    title: 'Đổi Mới Và Chính Sách Xã Hội Văn Hóa',
    author: 'Trần Độ',
    publish_year: 1988,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Chính Sách Đổi Mới',
    price: 30000,
    condition_note: 'Ấn bản 1988, bìa trắng ngà thiết kế trang nhã, in typo rõ ràng, gáy vững',
    summary: 'Tác phẩm phân tích sâu sắc các chính sách xã hội và văn hóa trong thời kỳ đổi mới do Trung tướng Trần Độ biên soạn.',
    quote: 'Đổi mới không chỉ là thay đổi kinh tế, mà còn là cuộc cách mạng trong tư duy văn hóa và xã hội.',
    cover_image_url: '/book-doi-moi.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 8,
    qr_code: 'BSNM-008',
    title: 'Khoảng Trống Có Hàng Ngàn Ngôi Sao',
    author: 'Văn Lê',
    publish_year: 1985,
    publisher: 'NXB Phụ Nữ',
    category: 'Truyện Dài & Văn Học Kháng Chiến',
    price: 35000,
    condition_note: 'Ấn bản gốc NXB Phụ Nữ, bìa giấy craft xưa in chữ nghệ thuật cách điệu và họa tiết những vì sao, gáy chắc chắn',
    summary: 'Truyện dài sâu lắng của nhà văn chiến sĩ Văn Lê (Lê Chí Thụy) do Nhà xuất bản Phụ nữ ấn hành. Tác phẩm khắc họa thế giới nội tâm và những khoảng lặng đầy chất thơ của tuổi trẻ nơi chiến trường khốc liệt.',
    quote: 'Dẫu cuộc đời có những khoảng trống chia lìa, trên bầu trời tâm hồn vẫn luôn lấp lánh hàng ngàn ngôi sao của lý tưởng và tình yêu thương.',
    cover_image_url: '/book-khoang-trong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 9,
    qr_code: 'BSNM-009',
    title: 'Cù Lao Tràm',
    author: 'Nguyễn Mạnh Tuấn',
    publish_year: 1985,
    publisher: 'NXB Văn Nghệ TP. Hồ Chí Minh',
    category: 'Tiểu Thuyết Xã Hội',
    price: 35000,
    condition_note: 'Ấn bản gốc 1985, bìa sờn cổ kính với họa tiết xanh lá đặc trưng miền sông nước, ruột nguyên vẹn',
    summary: 'Tiểu thuyết nổi tiếng của nhà văn Nguyễn Mạnh Tuấn, phản ánh chân thực các vấn đề kinh tế, xã hội và con người ở nông thôn miền Tây Nam Bộ sau ngày giải phóng.',
    quote: 'Cù lao giữa dòng sông như một ốc đảo thu nhỏ của xã hội, nơi mọi mâu thuẫn và khát vọng đổi thay đều hiện ra rõ ràng nhất.',
    cover_image_url: '/book-cu-lao-tram.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 10,
    qr_code: 'BSNM-010',
    title: 'Thư Vào Nam',
    author: 'Lê Duẩn',
    publish_year: 1985,
    publisher: 'NXB Sự Thật',
    category: 'Lịch Sử & Tư Liệu Cách Mạng',
    price: 35000,
    condition_note: 'Ấn bản lần đầu 1985 NXB Sự Thật, bìa giấy ngả vàng mộc mạc, chữ in typo nguyên gốc, gáy vững',
    summary: 'Tập hợp những lá thư và bức điện mật mà Tổng Bí thư Lê Duẩn đã gửi tới các cán bộ lãnh đạo tại chiến trường miền Nam trong suốt giai đoạn kháng chiến chống Mỹ (1961–1975).',
    quote: 'Những lá thư gửi vào Nam không chỉ là mệnh lệnh chiến đấu, mà còn là nhịp đập của trái tim luôn hướng về miền Nam ruột thịt.',
    cover_image_url: '/book-thu-vao-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 11,
    qr_code: 'BSNM-011',
    title: 'Hợp Tuyển Thơ Văn Việt Nam (1858 - 1920) — Quyển II',
    author: 'Huỳnh Lý (Chủ biên) - Viện Văn Học',
    publish_year: 1984,
    publisher: 'NXB Văn Học',
    category: 'Thơ Văn & Tư Liệu Lịch Sử',
    price: 35000,
    condition_note: 'Ấn bản Quyển II (1984) của NXB Văn Học, bìa vàng đất sờn gáy cổ kính, giấy mộc thời bao cấp ngả vàng nhuốm màu thời gian, chữ in sắc nét',
    summary: 'Công trình học thuật đồ sộ và chuẩn mực do Viện Văn học biên soạn (Huỳnh Lý chủ biên cùng các học giả uy tín). Sách tuyển chọn và khảo cứu sâu sắc các áng thơ văn yêu nước tiêu biểu của dân tộc giai đoạn giao thời biến động (1858 - 1920), thể hiện khí phách kiên trung, tư tưởng canh tân và hồn cốt văn chương nước nhà.',
    quote: 'Mỗi trang thơ văn giai đoạn 1858 - 1920 không chỉ là nghệ thuật ngôn từ, mà là tiếng lòng yêu nước, là khí phách quật cường của những bậc chí sĩ tiền bối.',
    cover_image_url: '/book-hop-tuyen-tho-van.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 12,
    qr_code: 'BSNM-012',
    title: 'Tơ Vương (Tập 2)',
    author: 'Vân Nhi',
    publish_year: 1989,
    publisher: 'NXB Văn Nghệ',
    category: 'Tiểu Thuyết & Tình Cảm Tuổi Trẻ',
    price: 30000,
    condition_note: 'Bìa màu vintage thập niên 80-90 ghim gáy nguyên bản, sờn mép thời gian, màu ảnh mang đậm hoài niệm tuổi học trò',
    summary: 'Tiểu thuyết tâm lý tình cảm giàu chất thơ của tác giả Vân Nhi. Câu chuyện xoay quanh những mối tơ vương tinh khôi, những rung động sâu kín và trăn trở trưởng thành của thế hệ thanh niên trí thức cuối thập niên 80, đan xen giữa ước mơ hoài bão và tình yêu trong sáng.',
    quote: 'Tuổi trẻ như một khúc dạo đầu êm đềm, dẫu mang bao mối tơ vương vương vấn vẫn giữ vẹn nguyên sự thánh thiện của tâm hồn.',
    cover_image_url: '/book-to-vuong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 13,
    qr_code: 'BSNM-013',
    title: 'Gặp Gỡ Cuối Năm & Thời Gian Của Người',
    author: 'Nguyễn Khải',
    publish_year: 1985,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản nguyên bản NXB Tác Phẩm Mới (TPM) năm 1985, bìa hai mảng màu vàng - nâu sờn mép phong trần, ruột nguyên vẹn, gáy chắc',
    summary: "Tập hợp hai kiệt tác tiểu thuyết đỉnh cao của nhà văn Nguyễn Khải - người từng nhận Giải thưởng Hồ Chí Minh về Văn học Nghệ thuật. 'Gặp gỡ cuối năm' (Giải thưởng Hội Nhà văn 1982) và 'Thời gian của người' là những trang văn sắc sảo, đối thoại triết lý sâu cay về nhân tâm, sự biến thiên của lịch sử và bản lĩnh con người thời hậu chiến.",
    quote: 'Thời gian không làm mất đi những giá trị chân chính; trong cuộc gặp gỡ giữa các số phận, sự thấu hiểu và lòng nhân ái là điều còn lại sau cùng.',
    cover_image_url: '/book-gap-go-cuoi-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 14,
    qr_code: 'BSNM-014',
    title: 'Mô Da (Cuộc Đời & Sự Nghiệp W. A. Mozart)',
    author: 'Bằng Việt',
    publish_year: 1978,
    publisher: 'NXB Văn Hóa',
    category: 'Âm Nhạc & Tiểu Sử Danh Nhân',
    price: 35000,
    condition_note: 'Ấn bản quý hiếm của NXB Văn Hóa, bìa xanh lam cổ điển in chân dung Wolfgang Amadeus Mozart trong khung oval trang nhã, dấu thư viện xưa, gáy nguyên vẹn',
    summary: 'Cuốn sách tiểu sử nghệ thuật đầu tiên và kinh điển tại Việt Nam viết về thiên tài âm nhạc Wolfgang Amadeus Mozart, do nhà thơ danh tiếng Bằng Việt biên soạn bằng ngòi bút tài hoa và tình yêu âm nhạc sâu sắc. Tác phẩm tái hiện sống động cuộc đời thần đồng rực rỡ nhưng cũng đầy thăng trầm, bi kịch của Mozart.',
    quote: 'Âm nhạc của Mozart là ánh sáng thuần khiết nhất rọi vào tâm hồn nhân loại, nơi mọi nỗi đau đời đều hóa thành thanh âm vĩnh cửu.',
    cover_image_url: '/book-mo-da.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 15,
    qr_code: 'BSNM-015',
    title: 'Mái Nhà Xanh',
    author: 'Hoàng Minh Nhân',
    publish_year: 1985,
    publisher: 'NXB Thanh Niên',
    category: 'Truyện Ký & Đời Sống Tuổi Trẻ',
    price: 30000,
    condition_note: 'Ấn bản gốc NXB Thanh Niên năm 1985, bìa minh họa phong cách tranh khắc gỗ ấn tượng ba gương mặt thanh niên, giấy bãi bằng ngả vàng mộc mạc',
    summary: "Tập truyện ký tiêu biểu của nhà văn chiến sĩ Hoàng Minh Nhân do NXB Thanh Niên ấn hành. Bằng lối văn chân thật, tác phẩm kể về những người trẻ giàu nhiệt huyết, cùng nhau dựng xây 'mái nhà xanh' của tình đồng đội, lao động và lý tưởng sống cống hiến trong những năm tháng khó khăn của đất nước.",
    quote: 'Dưới mái nhà chung ấm áp của tình thương và lý tưởng, tuổi trẻ tìm thấy ý nghĩa trọn vẹn nhất của cuộc đời mình.',
    cover_image_url: '/book-mai-nha-xanh.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 16,
    qr_code: 'BSNM-016',
    title: 'Đấu Tranh Chống Tệ Quan Liêu',
    author: 'Thiện Nhân',
    publish_year: 1983,
    publisher: 'NXB Sự Thật Hà Nội',
    category: 'Chính Luận & Tư Tưởng Xã Hội',
    price: 30000,
    condition_note: 'Ấn bản nguyên gốc năm 1983 của NXB Sự Thật, bìa giấy mộc màu nâu đất, chữ in typo đỏ - đen nổi bật, sờn mép thời bao cấp, gáy chắc chắn',
    summary: 'Tác phẩm chính luận quan trọng của tác giả Thiện Nhân do NXB Sự Thật ấn hành năm 1983. Cuốn sách thẳng thắn mổ xẻ hiện tượng quan liêu, hách dịch, giấy tờ trì trệ trong bộ máy hành chính và quản lý thời kỳ bao cấp; đề xuất các giải pháp nâng cao kỷ luật, phục vụ nhân dân, mở đường cho tư duy cải cách trước thềm Đại hội Đổi Mới 1986.',
    quote: 'Kiên quyết đấu tranh chống tệ quan liêu là điều kiện tiên quyết để bảo vệ niềm tin của nhân dân và xây dựng bộ máy phụng sự đất nước.',
    cover_image_url: '/book-dau-tranh-chong-te-quan-lieu.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 17,
    qr_code: 'BSNM-017',
    title: 'Nếu Ngày Mai Anh Chết',
    author: 'Luítx Rôhêliô Nôghêrátx (Luis Rogelio Nogueras)',
    publish_year: 1987,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Tiểu Thuyết Trinh Thám & Tình Báo',
    price: 35000,
    condition_note: 'Ấn bản tiếng Việt năm 1987, bìa tranh vẽ đồ họa trừu tượng phong cách mỹ thuật thập niên 80, sờn mép mộc mạc, giấy bãi bằng vàng đều',
    summary: "Kiệt tác tiểu thuyết trinh thám tình báo kinh điển của nhà văn Cuba lừng danh Luis Rogelio Nogueras (nguyên tác 'Y si mañana me muero'). Câu chuyện nghẹt thở xoay quanh những chiến sĩ tình báo hoạt động bí mật, đối đầu căng thẳng với mạng lưới gián điệp tinh vi, khắc họa sự hy sinh thầm lặng và lòng trung thành kiên định.",
    quote: 'Dù ngày mai có phải hy sinh, lý tưởng cao cả và tình yêu cuộc sống này sẽ mãi là ngọn lửa cháy rực không bao giờ tắt.',
    cover_image_url: '/book-neu-ngay-mai-anh-chet.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 18,
    qr_code: 'BSNM-018',
    title: 'Mùa Về Trong Thành Phố',
    author: 'Nhiều Tác Giả (Tủ Sách Tuổi Mới Lớn)',
    publish_year: 2004,
    publisher: 'NXB Trẻ',
    category: 'Truyện Ngắn & Tuổi Học Trò',
    price: 25000,
    condition_note: 'Ấn bản Tủ sách Tuổi Mới Lớn của NXB Trẻ, bìa đỏ nâu hoa hoàng anh hoài niệm, sờn mép nhẹ, ruột sách sạch đẹp nguyên vẹn',
    summary: 'Tập truyện ngắn tinh khôi gồm 16 câu chuyện của 8 cây bút nữ thuộc Tủ sách Tuổi Mới Lớn của NXB Trẻ. Tác phẩm gom góp những mảnh ghép ký ức học trò trong sáng, những mùa thay lá xao xuyến và kỷ niệm mùa hè ùa về trong lòng phố thị, mang đến cho người đọc cảm xúc bồi hồi về một thời áo trắng đã qua.',
    quote: 'Mùa về đánh thức những góc phố thân quen, nhắc nhở ta về những rung động trong veo và năm tháng tuổi trẻ không thể nào quên.',
    cover_image_url: '/book-mua-ve-trong-thanh-pho.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 19,
    qr_code: 'BSNM-019',
    title: 'Jăng Krixtốp (Jean-Christophe) — Tập I',
    author: 'Rômanh Rôlăng (Romain Rolland)',
    publish_year: 1983,
    publisher: 'NXB Văn Học',
    category: 'Văn Học Kinh Điển Thế Giới',
    price: 40000,
    condition_note: 'Ấn bản Tập I kinh điển của NXB Văn Học, bìa vàng - xanh rêu sờn gáy cổ kính, dấu thư viện xưa, giấy ngả vàng nhuốm màu lịch sử',
    summary: 'Bộ tiểu thuyết sử thi trường thiên vĩ đại gồm 10 tập của đại văn hào Pháp Romain Rolland – tác phẩm đã mang về cho ông Giải Nobel Văn học năm 1915. Sách khắc họa cuộc đời người nhạc sĩ thiên tài Jean-Christophe từ thuở ấu thơ đến lúc trưởng thành, là bản anh hùng ca bất diệt về nghệ thuật, khát vọng tự do và tình bác ái nhân loại.',
    quote: 'Tạo ra cái đẹp là chinh phục cái chết. Hãy sống và sáng tạo bằng tất cả ngọn lửa cháy bỏng trong trái tim mình.',
    cover_image_url: '/book-jang-krixtop.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 20,
    qr_code: 'BSNM-020',
    title: 'Chiếc Khuy Đồng',
    author: 'Ô-va-lốp (Lev Ovalov)',
    publish_year: 1982,
    publisher: 'NXB Thuận Hóa',
    category: 'Tiểu Thuyết Tình Báo Kinh Điển',
    price: 35000,
    condition_note: 'Ấn bản năm 1982 của NXB Thuận Hóa, bìa tranh vẽ người mang kính đen phong cách trinh thám Xô Viết, sờn rách mép gáy mộc mạc',
    summary: 'Cuốn tiểu thuyết tình báo kinh điển của nhà văn Liên Xô Lev Ovalov dựa trên sự kiện có thật tại thành phố Riga đầu Thế chiến II. Tác phẩm kể về cuộc đấu trí vô cùng căng thẳng, mạo hiểm giữa lực lượng phản gián Xô Viết và mạng lưới tình báo phương Tây xoay quanh manh mối kỳ bí là chiếc khuy áo bằng đồng.',
    quote: 'Trong bóng tối của những cuộc đấu trí vô hình, sự quả cảm và lòng trung kiên chính là ánh sáng dẫn lối cho người chiến sĩ.',
    cover_image_url: '/book-chiec-khuy-dong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 21,
    qr_code: 'BSNM-021',
    title: 'Ngôi Nhà Của Những Hồn Ma',
    author: 'Isaben Adendê (Isabel Allende)',
    publish_year: 1988,
    publisher: 'NXB Văn Học',
    category: 'Văn Học Mỹ Latinh & Hiện Thực Huyền Ảo',
    price: 40000,
    condition_note: 'Ấn bản nguyên gốc năm 1988 của NXB Văn Học, bìa vàng cam in họa tiết tranh khắc gỗ cổ điển, sờn mép mộc mạc, giấy bãi bằng ngả vàng đều',
    summary: "Kiệt tác tiểu thuyết hiện thực huyền ảo đầu tay chấn động văn đàn thế giới của nữ văn sĩ Chile lừng danh Isabel Allende (nguyên tác 'La casa de los espíritus'). Tác phẩm trải dài qua ba thế hệ của dòng họ Trueba, đan xen giữa tình yêu, số phận bi tráng, năng lực ngoại cảm kỳ diệu và những biến động lịch sử đẫm máu của đất nước Chile, được ví như 'Trăm năm cô đơn' của phái nữ.",
    quote: 'Ký ức là sợi dây mong manh nối liền cõi sống với những linh hồn đã khuất, để tình yêu và lòng kiêu hãnh không bao giờ bị thời gian vùi lấp.',
    cover_image_url: '/book-ngoi-nha-cua-nhung-hon-ma.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 22,
    qr_code: 'BSNM-022',
    title: 'Lửa Lạnh',
    author: 'Nhật Tuấn',
    publish_year: 1988,
    publisher: 'NXB Phụ Nữ',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản năm 1988 của NXB Phụ Nữ, bìa tranh vẽ gương mặt phụ nữ u buồn ấn tượng với nét vẽ typo đỏ - tím độc đáo, giấy thời bao cấp nhuốm màu thời gian',
    summary: "Tiểu thuyết đặc sắc của nhà văn Nhật Tuấn ra đời trong giai đoạn văn học khởi sắc đầu thời kỳ Đổi Mới. Tác phẩm đào sâu vào những góc khuất tâm lý, sự xung đột giữa khát vọng hạnh phúc cá nhân và những định kiến khắt khe của xã hội, miêu tả thứ 'ngọn lửa lạnh' âm ỉ thiêu đốt tâm hồn con người trước ngã rẽ cuộc đời.",
    quote: 'Có những ngọn lửa không bùng cháy rực rỡ mà âm ỉ lạnh giá, thiêu đốt tâm can con người giữa những giằng xé của số phận.',
    cover_image_url: '/book-lua-lanh.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 23,
    qr_code: 'BSNM-023',
    title: 'Cái Đầm Ma (La Mare au Diable)',
    author: 'Giorgio Xăng (George Sand)',
    publish_year: 1985,
    publisher: 'NXB Văn Học',
    category: 'Văn Học Kinh Điển Pháp',
    price: 35000,
    condition_note: 'Ấn bản NXB Văn Học, bìa giấy mộc màu nâu đất in minh họa chân dung hình học thanh lịch, sờn góc gáy nguyên bản, ruột sách sạch đẹp',
    summary: 'Kiệt tác tiểu thuyết đồng quê tiêu biểu nhất của nữ văn hào Pháp George Sand (Amantine Lucile Dupin). Tác phẩm mở ra bức tranh thiên nhiên tuyệt mỹ và câu chuyện tình yêu mộc mạc, thuần khiết giữa chàng nông dân Germain góa vợ và cô gái Marie nghèo khó bên chiếc đầm lầy ma quái, ca ngợi phẩm giá cao đẹp của những con người lao động lương thiện.',
    quote: 'Tình yêu chân chính không bao giờ cần đến sự giả dối hay tính toán; nó tỏa sáng giản dị như giọt sương mai trên cỏ nội đồng quê.',
    cover_image_url: '/book-cai-dam-ma.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 24,
    qr_code: 'BSNM-024',
    title: 'Đất Lành Nơi Người Lính Trở Về',
    author: 'Nhiều Tác Giả (Mai Linh Corporation tuyển chọn)',
    publish_year: 2005,
    publisher: 'NXB Thanh Niên',
    category: 'Ký Sự & Tri Ân Người Lính',
    price: 35000,
    condition_note: 'Bìa màu xanh lá biểu trưng hy vọng và hòa bình, hình ảnh nụ cười rạng rỡ của người lính và thế hệ trẻ, ruột in sạch đẹp, gáy chắc chắn',
    summary: "Tập ký sự và hồi ức xúc động do NXB Thanh Niên phối hợp phát hành, tôn vinh những người lính Cụ Hồ sau ngày đất nước hòa bình trở về với đời thường. Dù mang trên mình thương tật và ký ức chiến tranh khốc liệt, họ vẫn tiếp tục cống hiến trên mặt trận lao động xây dựng đất nước, gắn liền với tinh thần tri ân thương binh - bệnh binh sâu sắc của dự án Bìa Sờn Nắng Mới.",
    quote: 'Đất nước thanh bình là mảnh đất lành che chở cho những người lính trở về, nơi những vết thương chiến tranh được xoa dịu bằng tình thương và sự tri ân.',
    cover_image_url: '/book-dat-lanh-noi-nguoi-linh-tro-ve.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 25,
    qr_code: 'BSNM-025',
    title: 'Một Cõi Nhân Gian Bé Tí',
    author: 'Nguyễn Khải',
    publish_year: 1989,
    publisher: 'NXB Mũi Cà Mau',
    category: 'Tiểu Thuyết Chiêm Nghiệm & Đổi Mới',
    price: 35000,
    condition_note: 'Ấn bản nguyên bản năm 1989 của NXB Mũi Cà Mau (logo MCM), bìa tranh sơn dầu hoang hoải thời gian sờn mép phong trần, ruột nguyên vẹn',
    summary: "Một trong những tiểu thuyết chiêm nghiệm xuất sắc của nhà văn Nguyễn Khải (Giải thưởng Hồ Chí Minh) viết sau khi chuyển vào sinh sống tại miền Nam thời Đổi Mới. Bằng giọng văn điềm đạm, hóm hỉnh và sắc sảo, tác giả soi chiếu vào số phận những con người bình thường trong 'một cõi nhân gian bé tí' để tự vấn và đúc kết những quy luật sâu sắc về nhân tình thế thái.",
    quote: 'Cuộc đời dẫu chỉ là một cõi nhân gian bé tí, nhưng trong cõi ấy chứa đựng tất cả hỷ nộ ái ố và phẩm giá không thể trộn lẫn của con người.',
    cover_image_url: '/book-mot-coi-nhan-gian-be-ti.jpg',
    status: 'AVAILABLE'
  }
];

export const INITIAL_GUESTBOOK: GuestbookEntry[] = [];
