import { Book, CharityCampaign, GuestbookEntry } from './types';

export const INITIAL_CAMPAIGN: CharityCampaign = {
  campaign_name: 'Bìa Sờn Nắng Mới — Tri Ân Thương Binh Liệt Sĩ',
  beneficiary_name: 'Trung tâm Điều dưỡng Thương binh và Người có công Long Đất',
  beneficiary_address: 'Thị trấn Long Hải, huyện Long Điền, tỉnh Bà Rịa – Vũng Tàu',
  target_amount: 2000000,
};

export const INITIAL_BOOKS: Book[] = [
  {
    id: 1,
    qr_code: 'BSNM-001',
    title: 'Dì Hulia Và Nhà Văn Quèn',
    author: 'Mariô Vargax Lôxa (Mario Vargas Llosa)',
    publish_year: 1986,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Văn Học Dịch Thời Bao Cấp',
    price: 35000,
    condition_note: 'Bìa sờn mép nguyên bản, giấy bãi bằng ngả vàng thời kỳ 1986, gáy vững',
    summary: 'Kiệt tác hài hước tự truyện của đại văn hào giải Nobel Mario Vargas Llosa. Tác phẩm đan xen giữa mối tình sóng gió của chàng thanh niên Mario 18 tuổi với người dì họ Hulia, và những câu chuyện kịch truyền thanh kỳ lạ, đầy châm biếm sâu sắc của nhà biên kịch Pedro Camacho.',
    quote: 'Tình yêu và văn chương là hai điều cám dỗ lớn nhất của cuộc đời, khiến con người ta dám vượt qua mọi định kiến.',
    cover_image_url: '/book-di-julia.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 2,
    qr_code: 'BSNM-002',
    title: '40 Năm Văn Học (Tiểu Luận Phê Bình)',
    author: 'Nhiều tác giả (Bành Bảo, Hoàng Trung Thông, Hà Minh Đức...)',
    publish_year: 1986,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Lý Luận Phê Bình Văn Học',
    price: 35000,
    condition_note: 'Ấn bản kỷ niệm 40 năm văn học cách mạng (1945-1985), bìa sờn nhuộm màu thời gian, ruột nguyên vẹn',
    summary: 'Công trình tuyển tập tiểu luận phê bình đồ sộ tổng kết 40 năm chặng đường văn học cách mạng Việt Nam (1945 - 1985). Cuốn sách ghi lại những đánh giá cốt lõi về các tác phẩm đỉnh cao thời kỳ chống Pháp, chống Mỹ và những trăn trở đổi mới đầu tiên.',
    quote: 'Bốn mươi năm văn học là bốn mươi năm đồng hành cùng máu lửa non sông, nâng niu tâm hồn người chiến sĩ.',
    cover_image_url: '/book-40-nam-van-hoc.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 3,
    qr_code: 'BSNM-003',
    title: 'Kết Cục',
    author: 'Bô-rít Pô-lê-vôi (Boris Polevoy)',
    publish_year: 1985,
    publisher: 'NXB Quân Đội Nhân Dân',
    category: 'Ký Sự Chiến Tranh & Công Lý',
    price: 30000,
    condition_note: 'Bìa sờn mộc mạc, giấy in thời bao cấp nguyên vẹn chữ in typo của NXB Quân Đội Nhân Dân',
    summary: 'Tác phẩm lịch sử chấn động của nhà văn chiến sĩ Xô Viết Boris Polevoy, tường thuật lại toàn bộ quá trình Tòa án Quân sự Quốc tế Nuremberg xét xử tội phạm chiến tranh phát xít. Tác phẩm khẳng định công lý tất thắng của nhân loại tiến bộ trước bạo tàn.',
    quote: 'Tội ác chống lại loài người không bao giờ có thể bị lãng quên hay tha thứ trước tòa án lương tri.',
    cover_image_url: '/book-ket-cuc.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 4,
    qr_code: 'BSNM-004',
    title: 'Tìm Trầm',
    author: 'Minh Kiên',
    publish_year: 1987,
    publisher: 'NXB Văn Nghệ TP. Hồ Chí Minh',
    category: 'Tiểu Thuyết Đời Sống & Rừng Núi',
    price: 30000,
    condition_note: 'Ấn bản 1987, bìa nghệ thuật đồ họa thập niên 80 sờn nhẹ mép sách, các trang nguyên vẹn',
    summary: 'Tiểu thuyết khắc họa hành trình gian lao, sinh tử của những người phu trầm lặn lội giữa chốn rừng sâu núi thẳm miền Trung sau ngày giải phóng. Cuộc kiếm tìm kỳ nam quý giá đan xen với việc đi tìm chính nhân cách và giá trị lương thiện của con người giữa thử thách nghiệt ngã.',
    quote: 'Trầm hương sinh ra từ vết thương của cây dó bầu; đời người muốn tỏa hương cũng phải đi qua bao thăng trầm thử thách.',
    cover_image_url: '/book-tim-tram.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 5,
    qr_code: 'BSNM-005',
    title: 'Nắng Mới Trên Đỉnh Ăng-co',
    author: 'Hoàng Huân, Văn Lê, Đỗ Quảng, Nguyễn Việt Sơn, Nguyễn Khắc Viện',
    publish_year: 1981,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Ký Sự Tình Nghĩa Quốc Tế',
    price: 30000,
    condition_note: 'Bìa màu đất nguyên bản năm 1981, khắc họa bức phù điêu Angkor, gáy sờn cổ kính',
    summary: 'Tập ký sự chân thực và xúc động viết tại chiến trường Campuchia sau khi chế độ diệt chủng Khmer Đỏ bị lật đổ. Các tác giả ghi lại bước chân nghĩa tình của bộ đội tình nguyện Việt Nam giúp nhân dân bạn hồi sinh từ cõi chết, làm bừng sáng lại ánh nắng trên kỳ quan Angkor kỳ vĩ.',
    quote: 'Tia nắng mới rọi trên đỉnh tháp cổ không chỉ báo hiệu một ngày mới, mà là sự hồi sinh của cả một dân tộc được cứu thoát khỏi diệt chủng.',
    cover_image_url: '/book-nang-moi-ang-co.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 6,
    qr_code: 'BSNM-006',
    title: 'Thành Phố Hồ Chí Minh 10 Năm',
    author: 'Nguyễn Văn Linh',
    publish_year: 1985,
    publisher: 'NXB Sự Thật Hà Nội',
    category: 'Chính Trị & Xây Dựng Đất Nước',
    price: 30000,
    condition_note: 'Ấn bản gốc NXB Sự Thật 1985, bìa đỏ cờ cách mạng sờn nhẹ mép, ruột nguyên vẹn',
    summary: 'Tác phẩm chính trị quan trọng tổng kết 10 năm xây dựng Thành phố Hồ Chí Minh sau ngày giải phóng (1975-1985). Sách phân tích các thành tựu, thách thức và bài học kinh nghiệm trong quá trình cải tạo và phát triển thành phố.',
    quote: 'Mười năm xây dựng là mười năm cả thành phố cùng đồng lòng, biến hoang tàn thành hoa trái cho thế hệ mai sau.',
    cover_image_url: '/book-hcm-10-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 7,
    qr_code: 'BSNM-007',
    title: 'Đổi Mới Và Chính Sách Xã Hội Văn Hóa',
    author: 'Trần Độ',
    publish_year: 1988,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Chính Sách Đổi Mới',
    price: 30000,
    condition_note: 'Ấn bản 1988, bìa trắng ngà thiết kế trang nhã, in typo rõ ràng, gáy vững',
    summary: 'Tác phẩm phân tích sâu sắc các chính sách xã hội và văn hóa trong thời kỳ đổi mới do Trung tướng Trần Độ biên soạn.',
    quote: 'Đổi mới không chỉ là thay đổi kinh tế, mà còn là cuộc cách mạng trong tư duy văn hóa và xã hội.',
    cover_image_url: '/book-doi-moi.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 8,
    qr_code: 'BSNM-008',
    title: 'Khoảng Trống Có Hàng Ngàn Ngôi Sao',
    author: 'Văn Lê',
    publish_year: 1985,
    publisher: 'NXB Phụ Nữ',
    category: 'Truyện Dài & Văn Học Kháng Chiến',
    price: 35000,
    condition_note: 'Ấn bản gốc NXB Phụ Nữ, bìa giấy craft xưa in chữ nghệ thuật cách điệu và họa tiết những vì sao, gáy chắc chắn',
    summary: 'Truyện dài sâu lắng của nhà văn chiến sĩ Văn Lê (Lê Chí Thụy) do Nhà xuất bản Phụ nữ ấn hành. Tác phẩm khắc họa thế giới nội tâm và những khoảng lặng đầy chất thơ của tuổi trẻ nơi chiến trường khốc liệt.',
    quote: 'Dẫu cuộc đời có những khoảng trống chia lìa, trên bầu trời tâm hồn vẫn luôn lấp lánh hàng ngàn ngôi sao của lý tưởng và tình yêu thương.',
    cover_image_url: '/book-khoang-trong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 9,
    qr_code: 'BSNM-009',
    title: 'Cù Lao Tràm',
    author: 'Nguyễn Mạnh Tuấn',
    publish_year: 1985,
    publisher: 'NXB Văn Nghệ TP. Hồ Chí Minh',
    category: 'Tiểu Thuyết Xã Hội',
    price: 35000,
    condition_note: 'Ấn bản gốc 1985, bìa sờn cổ kính với họa tiết xanh lá đặc trưng miền sông nước, ruột nguyên vẹn',
    summary: 'Tiểu thuyết nổi tiếng của nhà văn Nguyễn Mạnh Tuấn, phản ánh chân thực các vấn đề kinh tế, xã hội và con người ở nông thôn miền Tây Nam Bộ sau ngày giải phóng.',
    quote: 'Cù lao giữa dòng sông như một ốc đảo thu nhỏ của xã hội, nơi mọi mâu thuẫn và khát vọng đổi thay đều hiện ra rõ ràng nhất.',
    cover_image_url: '/book-cu-lao-tram.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 10,
    qr_code: 'BSNM-010',
    title: 'Thư Vào Nam',
    author: 'Lê Duẩn',
    publish_year: 1985,
    publisher: 'NXB Sự Thật',
    category: 'Lịch Sử & Tư Liệu Cách Mạng',
    price: 35000,
    condition_note: 'Ấn bản lần đầu 1985 NXB Sự Thật, bìa giấy ngả vàng mộc mạc, chữ in typo nguyên gốc, gáy vững',
    summary: 'Tập hợp những lá thư và bức điện mật mà Tổng Bí thư Lê Duẩn đã gửi tới các cán bộ lãnh đạo tại chiến trường miền Nam trong suốt giai đoạn kháng chiến chống Mỹ (1961–1975).',
    quote: 'Những lá thư gửi vào Nam không chỉ là mệnh lệnh chiến đấu, mà còn là nhịp đập của trái tim luôn hướng về miền Nam ruột thịt.',
    cover_image_url: '/book-thu-vao-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 11,
    qr_code: 'BSNM-011',
    title: 'Hợp Tuyển Thơ Văn Việt Nam (1858 - 1920) — Quyển II',
    author: 'Huỳnh Lý (Chủ biên) - Viện Văn Học',
    publish_year: 1984,
    publisher: 'NXB Văn Học',
    category: 'Thơ Văn & Tư Liệu Lịch Sử',
    price: 35000,
    condition_note: 'Ấn bản Quyển II (1984) của NXB Văn Học, bìa vàng đất sờn gáy cổ kính, giấy mộc thời bao cấp ngả vàng nhuốm màu thời gian, chữ in sắc nét',
    summary: 'Công trình học thuật đồ sộ và chuẩn mực do Viện Văn học biên soạn (Huỳnh Lý chủ biên cùng các học giả uy tín). Sách tuyển chọn và khảo cứu sâu sắc các áng thơ văn yêu nước tiêu biểu của dân tộc giai đoạn giao thời biến động (1858 - 1920), thể hiện khí phách kiên trung, tư tưởng canh tân và hồn cốt văn chương nước nhà.',
    quote: 'Mỗi trang thơ văn giai đoạn 1858 - 1920 không chỉ là nghệ thuật ngôn từ, mà là tiếng lòng yêu nước, là khí phách quật cường của những bậc chí sĩ tiền bối.',
    cover_image_url: '/book-hop-tuyen-tho-van.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 12,
    qr_code: 'BSNM-012',
    title: 'Tơ Vương (Tập 2)',
    author: 'Vân Nhi',
    publish_year: 1989,
    publisher: 'NXB Văn Nghệ',
    category: 'Tiểu Thuyết & Tình Cảm Tuổi Trẻ',
    price: 30000,
    condition_note: 'Bìa màu vintage thập niên 80-90 ghim gáy nguyên bản, sờn mép thời gian, màu ảnh mang đậm hoài niệm tuổi học trò',
    summary: 'Tiểu thuyết tâm lý tình cảm giàu chất thơ của tác giả Vân Nhi. Câu chuyện xoay quanh những mối tơ vương tinh khôi, những rung động sâu kín và trăn trở trưởng thành của thế hệ thanh niên trí thức cuối thập niên 80, đan xen giữa ước mơ hoài bão và tình yêu trong sáng.',
    quote: 'Tuổi trẻ như một khúc dạo đầu êm đềm, dẫu mang bao mối tơ vương vương vấn vẫn giữ vẹn nguyên sự thánh thiện của tâm hồn.',
    cover_image_url: '/book-to-vuong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 13,
    qr_code: 'BSNM-013',
    title: 'Gặp Gỡ Cuối Năm & Thời Gian Của Người',
    author: 'Nguyễn Khải',
    publish_year: 1985,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản nguyên bản NXB Tác Phẩm Mới (TPM) năm 1985, bìa hai mảng màu vàng - nâu sờn mép phong trần, ruột nguyên vẹn, gáy chắc',
    summary: "Tập hợp hai kiệt tác tiểu thuyết đỉnh cao của nhà văn Nguyễn Khải - người từng nhận Giải thưởng Hồ Chí Minh về Văn học Nghệ thuật. 'Gặp gỡ cuối năm' (Giải thưởng Hội Nhà văn 1982) và 'Thời gian của người' là những trang văn sắc sảo, đối thoại triết lý sâu cay về nhân tâm, sự biến thiên của lịch sử và bản lĩnh con người thời hậu chiến.",
    quote: 'Thời gian không làm mất đi những giá trị chân chính; trong cuộc gặp gỡ giữa các số phận, sự thấu hiểu và lòng nhân ái là điều còn lại sau cùng.',
    cover_image_url: '/book-gap-go-cuoi-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 14,
    qr_code: 'BSNM-014',
    title: 'Mô Da (Cuộc Đời & Sự Nghiệp W. A. Mozart)',
    author: 'Bằng Việt',
    publish_year: 1978,
    publisher: 'NXB Văn Hóa',
    category: 'Âm Nhạc & Tiểu Sử Danh Nhân',
    price: 35000,
    condition_note: 'Ấn bản quý hiếm của NXB Văn Hóa, bìa xanh lam cổ điển in chân dung Wolfgang Amadeus Mozart trong khung oval trang nhã, dấu thư viện xưa, gáy nguyên vẹn',
    summary: 'Cuốn sách tiểu sử nghệ thuật đầu tiên và kinh điển tại Việt Nam viết về thiên tài âm nhạc Wolfgang Amadeus Mozart, do nhà thơ danh tiếng Bằng Việt biên soạn bằng ngòi bút tài hoa và tình yêu âm nhạc sâu sắc. Tác phẩm tái hiện sống động cuộc đời thần đồng rực rỡ nhưng cũng đầy thăng trầm, bi kịch của Mozart.',
    quote: 'Âm nhạc của Mozart là ánh sáng thuần khiết nhất rọi vào tâm hồn nhân loại, nơi mọi nỗi đau đời đều hóa thành thanh âm vĩnh cửu.',
    cover_image_url: '/book-mo-da.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 15,
    qr_code: 'BSNM-015',
    title: 'Mái Nhà Xanh',
    author: 'Hoàng Minh Nhân',
    publish_year: 1985,
    publisher: 'NXB Thanh Niên',
    category: 'Truyện Ký & Đời Sống Tuổi Trẻ',
    price: 30000,
    condition_note: 'Ấn bản gốc NXB Thanh Niên năm 1985, bìa minh họa phong cách tranh khắc gỗ ấn tượng ba gương mặt thanh niên, giấy bãi bằng ngả vàng mộc mạc',
    summary: "Tập truyện ký tiêu biểu của nhà văn chiến sĩ Hoàng Minh Nhân do NXB Thanh Niên ấn hành. Bằng lối văn chân thật, tác phẩm kể về những người trẻ giàu nhiệt huyết, cùng nhau dựng xây 'mái nhà xanh' của tình đồng đội, lao động và lý tưởng sống cống hiến trong những năm tháng khó khăn của đất nước.",
    quote: 'Dưới mái nhà chung ấm áp của tình thương và lý tưởng, tuổi trẻ tìm thấy ý nghĩa trọn vẹn nhất của cuộc đời mình.',
    cover_image_url: '/book-mai-nha-xanh.jpg',
    status: 'AVAILABLE'
  }
];

export const INITIAL_GUESTBOOK: GuestbookEntry[] = [];
