import { Book, CharityCampaign, GuestbookEntry } from './types';

export const INITIAL_CAMPAIGN: CharityCampaign = {
  campaign_name: 'Bìa Sờn Nắng Mới — Tri Ân Thương Binh Liệt Sĩ',
  beneficiary_name: 'Trung tâm Điều dưỡng Thương binh và Người có công Long Đất',
  beneficiary_address: 'Thị trấn Long Hải, huyện Long Điền, tỉnh Bà Rịa – Vũng Tàu',
  target_amount: 2000000,
};

export const INITIAL_BOOKS: Book[] = [
  {
    id: 1,
    qr_code: 'BSNM-001',
    title: 'Dì Hulia Và Nhà Văn Quèn',
    author: 'Mariô Vargax Lôxa (Mario Vargas Llosa)',
    publish_year: 1986,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Văn Học Dịch Thời Bao Cấp',
    price: 35000,
    condition_note: 'Bìa sờn mép nguyên bản, giấy bãi bằng ngả vàng thời kỳ 1986, gáy vững',
    summary: 'Kiệt tác hài hước tự truyện của đại văn hào giải Nobel Mario Vargas Llosa. Tác phẩm đan xen giữa mối tình sóng gió của chàng thanh niên Mario 18 tuổi với người dì họ Hulia, và những câu chuyện kịch truyền thanh kỳ lạ, đầy châm biếm sâu sắc của nhà biên kịch Pedro Camacho.',
    quote: 'Tình yêu và văn chương là hai điều cám dỗ lớn nhất của cuộc đời, khiến con người ta dám vượt qua mọi định kiến.',
    cover_image_url: '/book-di-julia.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 2,
    qr_code: 'BSNM-002',
    title: '40 Năm Văn Học (Tiểu Luận Phê Bình)',
    author: 'Nhiều tác giả (Bành Bảo, Hoàng Trung Thông, Hà Minh Đức...)',
    publish_year: 1986,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Lý Luận Phê Bình Văn Học',
    price: 35000,
    condition_note: 'Ấn bản kỷ niệm 40 năm văn học cách mạng (1945-1985), bìa sờn nhuộm màu thời gian, ruột nguyên vẹn',
    summary: 'Công trình tuyển tập tiểu luận phê bình đồ sộ tổng kết 40 năm chặng đường văn học cách mạng Việt Nam (1945 - 1985). Cuốn sách ghi lại những đánh giá cốt lõi về các tác phẩm đỉnh cao thời kỳ chống Pháp, chống Mỹ và những trăn trở đổi mới đầu tiên.',
    quote: 'Bốn mươi năm văn học là bốn mươi năm đồng hành cùng máu lửa non sông, nâng niu tâm hồn người chiến sĩ.',
    cover_image_url: '/book-40-nam-van-hoc.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 3,
    qr_code: 'BSNM-003',
    title: 'Kết Cục',
    author: 'Bô-rít Pô-lê-vôi (Boris Polevoy)',
    publish_year: 1985,
    publisher: 'NXB Quân Đội Nhân Dân',
    category: 'Ký Sự Chiến Tranh & Công Lý',
    price: 30000,
    condition_note: 'Bìa sờn mộc mạc, giấy in thời bao cấp nguyên vẹn chữ in typo của NXB Quân Đội Nhân Dân',
    summary: 'Tác phẩm lịch sử chấn động của nhà văn chiến sĩ Xô Viết Boris Polevoy, tường thuật lại toàn bộ quá trình Tòa án Quân sự Quốc tế Nuremberg xét xử tội phạm chiến tranh phát xít. Tác phẩm khẳng định công lý tất thắng của nhân loại tiến bộ trước bạo tàn.',
    quote: 'Tội ác chống lại loài người không bao giờ có thể bị lãng quên hay tha thứ trước tòa án lương tri.',
    cover_image_url: '/book-ket-cuc.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 4,
    qr_code: 'BSNM-004',
    title: 'Tìm Trầm',
    author: 'Minh Kiên',
    publish_year: 1987,
    publisher: 'NXB Văn Nghệ TP. Hồ Chí Minh',
    category: 'Tiểu Thuyết Đời Sống & Rừng Núi',
    price: 30000,
    condition_note: 'Ấn bản 1987, bìa nghệ thuật đồ họa thập niên 80 sờn nhẹ mép sách, các trang nguyên vẹn',
    summary: 'Tiểu thuyết khắc họa hành trình gian lao, sinh tử của những người phu trầm lặn lội giữa chốn rừng sâu núi thẳm miền Trung sau ngày giải phóng. Cuộc kiếm tìm kỳ nam quý giá đan xen với việc đi tìm chính nhân cách và giá trị lương thiện của con người giữa thử thách nghiệt ngã.',
    quote: 'Trầm hương sinh ra từ vết thương của cây dó bầu; đời người muốn tỏa hương cũng phải đi qua bao thăng trầm thử thách.',
    cover_image_url: '/book-tim-tram.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 5,
    qr_code: 'BSNM-005',
    title: 'Nắng Mới Trên Đỉnh Ăng-co',
    author: 'Hoàng Huân, Văn Lê, Đỗ Quảng, Nguyễn Việt Sơn, Nguyễn Khắc Viện',
    publish_year: 1981,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Ký Sự Tình Nghĩa Quốc Tế',
    price: 30000,
    condition_note: 'Bìa màu đất nguyên bản năm 1981, khắc họa bức phù điêu Angkor, gáy sờn cổ kính',
    summary: 'Tập ký sự chân thực và xúc động viết tại chiến trường Campuchia sau khi chế độ diệt chủng Khmer Đỏ bị lật đổ. Các tác giả ghi lại bước chân nghĩa tình của bộ đội tình nguyện Việt Nam giúp nhân dân bạn hồi sinh từ cõi chết, làm bừng sáng lại ánh nắng trên kỳ quan Angkor kỳ vĩ.',
    quote: 'Tia nắng mới rọi trên đỉnh tháp cổ không chỉ báo hiệu một ngày mới, mà là sự hồi sinh của cả một dân tộc được cứu thoát khỏi diệt chủng.',
    cover_image_url: '/book-nang-moi-ang-co.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 6,
    qr_code: 'BSNM-006',
    title: 'Thành Phố Hồ Chí Minh 10 Năm',
    author: 'Nguyễn Văn Linh',
    publish_year: 1985,
    publisher: 'NXB Sự Thật Hà Nội',
    category: 'Chính Trị & Xây Dựng Đất Nước',
    price: 30000,
    condition_note: 'Ấn bản gốc NXB Sự Thật 1985, bìa đỏ cờ cách mạng sờn nhẹ mép, ruột nguyên vẹn',
    summary: 'Tác phẩm chính trị quan trọng tổng kết 10 năm xây dựng Thành phố Hồ Chí Minh sau ngày giải phóng (1975-1985). Sách phân tích các thành tựu, thách thức và bài học kinh nghiệm trong quá trình cải tạo và phát triển thành phố.',
    quote: 'Mười năm xây dựng là mười năm cả thành phố cùng đồng lòng, biến hoang tàn thành hoa trái cho thế hệ mai sau.',
    cover_image_url: '/book-hcm-10-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 7,
    qr_code: 'BSNM-007',
    title: 'Đổi Mới Và Chính Sách Xã Hội Văn Hóa',
    author: 'Trần Độ',
    publish_year: 1988,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Chính Sách Đổi Mới',
    price: 30000,
    condition_note: 'Ấn bản 1988, bìa trắng ngà thiết kế trang nhã, in typo rõ ràng, gáy vững',
    summary: 'Tác phẩm phân tích sâu sắc các chính sách xã hội và văn hóa trong thời kỳ đổi mới do Trung tướng Trần Độ biên soạn.',
    quote: 'Đổi mới không chỉ là thay đổi kinh tế, mà còn là cuộc cách mạng trong tư duy văn hóa và xã hội.',
    cover_image_url: '/book-doi-moi.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 8,
    qr_code: 'BSNM-008',
    title: 'Khoảng Trống Có Hàng Ngàn Ngôi Sao',
    author: 'Văn Lê',
    publish_year: 1985,
    publisher: 'NXB Phụ Nữ',
    category: 'Truyện Dài & Văn Học Kháng Chiến',
    price: 35000,
    condition_note: 'Ấn bản gốc NXB Phụ Nữ, bìa giấy craft xưa in chữ nghệ thuật cách điệu và họa tiết những vì sao, gáy chắc chắn',
    summary: 'Truyện dài sâu lắng của nhà văn chiến sĩ Văn Lê (Lê Chí Thụy) do Nhà xuất bản Phụ nữ ấn hành. Tác phẩm khắc họa thế giới nội tâm và những khoảng lặng đầy chất thơ của tuổi trẻ nơi chiến trường khốc liệt.',
    quote: 'Dẫu cuộc đời có những khoảng trống chia lìa, trên bầu trời tâm hồn vẫn luôn lấp lánh hàng ngàn ngôi sao của lý tưởng và tình yêu thương.',
    cover_image_url: '/book-khoang-trong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 9,
    qr_code: 'BSNM-009',
    title: 'Cù Lao Tràm',
    author: 'Nguyễn Mạnh Tuấn',
    publish_year: 1985,
    publisher: 'NXB Văn Nghệ TP. Hồ Chí Minh',
    category: 'Tiểu Thuyết Xã Hội',
    price: 35000,
    condition_note: 'Ấn bản gốc 1985, bìa sờn cổ kính với họa tiết xanh lá đặc trưng miền sông nước, ruột nguyên vẹn',
    summary: 'Tiểu thuyết nổi tiếng của nhà văn Nguyễn Mạnh Tuấn, phản ánh chân thực các vấn đề kinh tế, xã hội và con người ở nông thôn miền Tây Nam Bộ sau ngày giải phóng.',
    quote: 'Cù lao giữa dòng sông như một ốc đảo thu nhỏ của xã hội, nơi mọi mâu thuẫn và khát vọng đổi thay đều hiện ra rõ ràng nhất.',
    cover_image_url: '/book-cu-lao-tram.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 10,
    qr_code: 'BSNM-010',
    title: 'Thư Vào Nam',
    author: 'Lê Duẩn',
    publish_year: 1985,
    publisher: 'NXB Sự Thật',
    category: 'Lịch Sử & Tư Liệu Cách Mạng',
    price: 35000,
    condition_note: 'Ấn bản lần đầu 1985 NXB Sự Thật, bìa giấy ngả vàng mộc mạc, chữ in typo nguyên gốc, gáy vững',
    summary: 'Tập hợp những lá thư và bức điện mật mà Tổng Bí thư Lê Duẩn đã gửi tới các cán bộ lãnh đạo tại chiến trường miền Nam trong suốt giai đoạn kháng chiến chống Mỹ (1961–1975).',
    quote: 'Những lá thư gửi vào Nam không chỉ là mệnh lệnh chiến đấu, mà còn là nhịp đập của trái tim luôn hướng về miền Nam ruột thịt.',
    cover_image_url: '/book-thu-vao-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 11,
    qr_code: 'BSNM-011',
    title: 'Hợp Tuyển Thơ Văn Việt Nam (1858 - 1920) — Quyển II',
    author: 'Huỳnh Lý (Chủ biên) - Viện Văn Học',
    publish_year: 1984,
    publisher: 'NXB Văn Học',
    category: 'Thơ Văn & Tư Liệu Lịch Sử',
    price: 35000,
    condition_note: 'Ấn bản Quyển II (1984) của NXB Văn Học, bìa vàng đất sờn gáy cổ kính, giấy mộc thời bao cấp ngả vàng nhuốm màu thời gian, chữ in sắc nét',
    summary: 'Công trình học thuật đồ sộ và chuẩn mực do Viện Văn học biên soạn (Huỳnh Lý chủ biên cùng các học giả uy tín). Sách tuyển chọn và khảo cứu sâu sắc các áng thơ văn yêu nước tiêu biểu của dân tộc giai đoạn giao thời biến động (1858 - 1920), thể hiện khí phách kiên trung, tư tưởng canh tân và hồn cốt văn chương nước nhà.',
    quote: 'Mỗi trang thơ văn giai đoạn 1858 - 1920 không chỉ là nghệ thuật ngôn từ, mà là tiếng lòng yêu nước, là khí phách quật cường của những bậc chí sĩ tiền bối.',
    cover_image_url: '/book-hop-tuyen-tho-van.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 12,
    qr_code: 'BSNM-012',
    title: 'Tơ Vương (Tập 2)',
    author: 'Vân Nhi',
    publish_year: 1989,
    publisher: 'NXB Văn Nghệ',
    category: 'Tiểu Thuyết & Tình Cảm Tuổi Trẻ',
    price: 30000,
    condition_note: 'Bìa màu vintage thập niên 80-90 ghim gáy nguyên bản, sờn mép thời gian, màu ảnh mang đậm hoài niệm tuổi học trò',
    summary: 'Tiểu thuyết tâm lý tình cảm giàu chất thơ của tác giả Vân Nhi. Câu chuyện xoay quanh những mối tơ vương tinh khôi, những rung động sâu kín và trăn trở trưởng thành của thế hệ thanh niên trí thức cuối thập niên 80, đan xen giữa ước mơ hoài bão và tình yêu trong sáng.',
    quote: 'Tuổi trẻ như một khúc dạo đầu êm đềm, dẫu mang bao mối tơ vương vương vấn vẫn giữ vẹn nguyên sự thánh thiện của tâm hồn.',
    cover_image_url: '/book-to-vuong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 13,
    qr_code: 'BSNM-013',
    title: 'Gặp Gỡ Cuối Năm & Thời Gian Của Người',
    author: 'Nguyễn Khải',
    publish_year: 1985,
    publisher: 'NXB Tác Phẩm Mới',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản nguyên bản NXB Tác Phẩm Mới (TPM) năm 1985, bìa hai mảng màu vàng - nâu sờn mép phong trần, ruột nguyên vẹn, gáy chắc',
    summary: "Tập hợp hai kiệt tác tiểu thuyết đỉnh cao của nhà văn Nguyễn Khải - người từng nhận Giải thưởng Hồ Chí Minh về Văn học Nghệ thuật. 'Gặp gỡ cuối năm' (Giải thưởng Hội Nhà văn 1982) và 'Thời gian của người' là những trang văn sắc sảo, đối thoại triết lý sâu cay về nhân tâm, sự biến thiên của lịch sử và bản lĩnh con người thời hậu chiến.",
    quote: 'Thời gian không làm mất đi những giá trị chân chính; trong cuộc gặp gỡ giữa các số phận, sự thấu hiểu và lòng nhân ái là điều còn lại sau cùng.',
    cover_image_url: '/book-gap-go-cuoi-nam.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 14,
    qr_code: 'BSNM-014',
    title: 'Mô Da (Cuộc Đời & Sự Nghiệp W. A. Mozart)',
    author: 'Bằng Việt',
    publish_year: 1978,
    publisher: 'NXB Văn Hóa',
    category: 'Âm Nhạc & Tiểu Sử Danh Nhân',
    price: 35000,
    condition_note: 'Ấn bản quý hiếm của NXB Văn Hóa, bìa xanh lam cổ điển in chân dung Wolfgang Amadeus Mozart trong khung oval trang nhã, dấu thư viện xưa, gáy nguyên vẹn',
    summary: 'Cuốn sách tiểu sử nghệ thuật đầu tiên và kinh điển tại Việt Nam viết về thiên tài âm nhạc Wolfgang Amadeus Mozart, do nhà thơ danh tiếng Bằng Việt biên soạn bằng ngòi bút tài hoa và tình yêu âm nhạc sâu sắc. Tác phẩm tái hiện sống động cuộc đời thần đồng rực rỡ nhưng cũng đầy thăng trầm, bi kịch của Mozart.',
    quote: 'Âm nhạc của Mozart là ánh sáng thuần khiết nhất rọi vào tâm hồn nhân loại, nơi mọi nỗi đau đời đều hóa thành thanh âm vĩnh cửu.',
    cover_image_url: '/book-mo-da.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 15,
    qr_code: 'BSNM-015',
    title: 'Mái Nhà Xanh',
    author: 'Hoàng Minh Nhân',
    publish_year: 1985,
    publisher: 'NXB Thanh Niên',
    category: 'Truyện Ký & Đời Sống Tuổi Trẻ',
    price: 30000,
    condition_note: 'Ấn bản gốc NXB Thanh Niên năm 1985, bìa minh họa phong cách tranh khắc gỗ ấn tượng ba gương mặt thanh niên, giấy bãi bằng ngả vàng mộc mạc',
    summary: "Tập truyện ký tiêu biểu của nhà văn chiến sĩ Hoàng Minh Nhân do NXB Thanh Niên ấn hành. Bằng lối văn chân thật, tác phẩm kể về những người trẻ giàu nhiệt huyết, cùng nhau dựng xây 'mái nhà xanh' của tình đồng đội, lao động và lý tưởng sống cống hiến trong những năm tháng khó khăn của đất nước.",
    quote: 'Dưới mái nhà chung ấm áp của tình thương và lý tưởng, tuổi trẻ tìm thấy ý nghĩa trọn vẹn nhất của cuộc đời mình.',
    cover_image_url: '/book-mai-nha-xanh.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 16,
    qr_code: 'BSNM-016',
    title: 'Đấu Tranh Chống Tệ Quan Liêu',
    author: 'Thiện Nhân',
    publish_year: 1983,
    publisher: 'NXB Sự Thật Hà Nội',
    category: 'Chính Luận & Tư Tưởng Xã Hội',
    price: 30000,
    condition_note: 'Ấn bản nguyên gốc năm 1983 của NXB Sự Thật, bìa giấy mộc màu nâu đất, chữ in typo đỏ - đen nổi bật, sờn mép thời bao cấp, gáy chắc chắn',
    summary: 'Tác phẩm chính luận quan trọng của tác giả Thiện Nhân do NXB Sự Thật ấn hành năm 1983. Cuốn sách thẳng thắn mổ xẻ hiện tượng quan liêu, hách dịch, giấy tờ trì trệ trong bộ máy hành chính và quản lý thời kỳ bao cấp; đề xuất các giải pháp nâng cao kỷ luật, phục vụ nhân dân, mở đường cho tư duy cải cách trước thềm Đại hội Đổi Mới 1986.',
    quote: 'Kiên quyết đấu tranh chống tệ quan liêu là điều kiện tiên quyết để bảo vệ niềm tin của nhân dân và xây dựng bộ máy phụng sự đất nước.',
    cover_image_url: '/book-dau-tranh-chong-te-quan-lieu.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 17,
    qr_code: 'BSNM-017',
    title: 'Nếu Ngày Mai Anh Chết',
    author: 'Luítx Rôhêliô Nôghêrátx (Luis Rogelio Nogueras)',
    publish_year: 1987,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Tiểu Thuyết Trinh Thám & Tình Báo',
    price: 35000,
    condition_note: 'Ấn bản tiếng Việt năm 1987, bìa tranh vẽ đồ họa trừu tượng phong cách mỹ thuật thập niên 80, sờn mép mộc mạc, giấy bãi bằng vàng đều',
    summary: "Kiệt tác tiểu thuyết trinh thám tình báo kinh điển của nhà văn Cuba lừng danh Luis Rogelio Nogueras (nguyên tác 'Y si mañana me muero'). Câu chuyện nghẹt thở xoay quanh những chiến sĩ tình báo hoạt động bí mật, đối đầu căng thẳng với mạng lưới gián điệp tinh vi, khắc họa sự hy sinh thầm lặng và lòng trung thành kiên định.",
    quote: 'Dù ngày mai có phải hy sinh, lý tưởng cao cả và tình yêu cuộc sống này sẽ mãi là ngọn lửa cháy rực không bao giờ tắt.',
    cover_image_url: '/book-neu-ngay-mai-anh-chet.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 18,
    qr_code: 'BSNM-018',
    title: 'Mùa Về Trong Thành Phố',
    author: 'Nhiều Tác Giả (Tủ Sách Tuổi Mới Lớn)',
    publish_year: 2004,
    publisher: 'NXB Trẻ',
    category: 'Truyện Ngắn & Tuổi Học Trò',
    price: 25000,
    condition_note: 'Ấn bản Tủ sách Tuổi Mới Lớn của NXB Trẻ, bìa đỏ nâu hoa hoàng anh hoài niệm, sờn mép nhẹ, ruột sách sạch đẹp nguyên vẹn',
    summary: 'Tập truyện ngắn tinh khôi gồm 16 câu chuyện của 8 cây bút nữ thuộc Tủ sách Tuổi Mới Lớn của NXB Trẻ. Tác phẩm gom góp những mảnh ghép ký ức học trò trong sáng, những mùa thay lá xao xuyến và kỷ niệm mùa hè ùa về trong lòng phố thị, mang đến cho người đọc cảm xúc bồi hồi về một thời áo trắng đã qua.',
    quote: 'Mùa về đánh thức những góc phố thân quen, nhắc nhở ta về những rung động trong veo và năm tháng tuổi trẻ không thể nào quên.',
    cover_image_url: '/book-mua-ve-trong-thanh-pho.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 19,
    qr_code: 'BSNM-019',
    title: 'Jăng Krixtốp (Jean-Christophe) — Tập I',
    author: 'Rômanh Rôlăng (Romain Rolland)',
    publish_year: 1983,
    publisher: 'NXB Văn Học',
    category: 'Văn Học Kinh Điển Thế Giới',
    price: 40000,
    condition_note: 'Ấn bản Tập I kinh điển của NXB Văn Học, bìa vàng - xanh rêu sờn gáy cổ kính, dấu thư viện xưa, giấy ngả vàng nhuốm màu lịch sử',
    summary: 'Bộ tiểu thuyết sử thi trường thiên vĩ đại gồm 10 tập của đại văn hào Pháp Romain Rolland – tác phẩm đã mang về cho ông Giải Nobel Văn học năm 1915. Sách khắc họa cuộc đời người nhạc sĩ thiên tài Jean-Christophe từ thuở ấu thơ đến lúc trưởng thành, là bản anh hùng ca bất diệt về nghệ thuật, khát vọng tự do và tình bác ái nhân loại.',
    quote: 'Tạo ra cái đẹp là chinh phục cái chết. Hãy sống và sáng tạo bằng tất cả ngọn lửa cháy bỏng trong trái tim mình.',
    cover_image_url: '/book-jang-krixtop.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 20,
    qr_code: 'BSNM-020',
    title: 'Chiếc Khuy Đồng',
    author: 'Ô-va-lốp (Lev Ovalov)',
    publish_year: 1982,
    publisher: 'NXB Thuận Hóa',
    category: 'Tiểu Thuyết Tình Báo Kinh Điển',
    price: 35000,
    condition_note: 'Ấn bản năm 1982 của NXB Thuận Hóa, bìa tranh vẽ người mang kính đen phong cách trinh thám Xô Viết, sờn rách mép gáy mộc mạc',
    summary: 'Cuốn tiểu thuyết tình báo kinh điển của nhà văn Liên Xô Lev Ovalov dựa trên sự kiện có thật tại thành phố Riga đầu Thế chiến II. Tác phẩm kể về cuộc đấu trí vô cùng căng thẳng, mạo hiểm giữa lực lượng phản gián Xô Viết và mạng lưới tình báo phương Tây xoay quanh manh mối kỳ bí là chiếc khuy áo bằng đồng.',
    quote: 'Trong bóng tối của những cuộc đấu trí vô hình, sự quả cảm và lòng trung kiên chính là ánh sáng dẫn lối cho người chiến sĩ.',
    cover_image_url: '/book-chiec-khuy-dong.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 21,
    qr_code: 'BSNM-021',
    title: 'Ngôi Nhà Của Những Hồn Ma',
    author: 'Isaben Adendê (Isabel Allende)',
    publish_year: 1988,
    publisher: 'NXB Văn Học',
    category: 'Văn Học Mỹ Latinh & Hiện Thực Huyền Ảo',
    price: 40000,
    condition_note: 'Ấn bản nguyên gốc năm 1988 của NXB Văn Học, bìa vàng cam in họa tiết tranh khắc gỗ cổ điển, sờn mép mộc mạc, giấy bãi bằng ngả vàng đều',
    summary: "Kiệt tác tiểu thuyết hiện thực huyền ảo đầu tay chấn động văn đàn thế giới của nữ văn sĩ Chile lừng danh Isabel Allende (nguyên tác 'La casa de los espíritus'). Tác phẩm trải dài qua ba thế hệ của dòng họ Trueba, đan xen giữa tình yêu, số phận bi tráng, năng lực ngoại cảm kỳ diệu và những biến động lịch sử đẫm máu của đất nước Chile, được ví như 'Trăm năm cô đơn' của phái nữ.",
    quote: 'Ký ức là sợi dây mong manh nối liền cõi sống với những linh hồn đã khuất, để tình yêu và lòng kiêu hãnh không bao giờ bị thời gian vùi lấp.',
    cover_image_url: '/book-ngoi-nha-cua-nhung-hon-ma.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 22,
    qr_code: 'BSNM-022',
    title: 'Lửa Lạnh',
    author: 'Nhật Tuấn',
    publish_year: 1988,
    publisher: 'NXB Phụ Nữ',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản năm 1988 của NXB Phụ Nữ, bìa tranh vẽ gương mặt phụ nữ u buồn ấn tượng với nét vẽ typo đỏ - tím độc đáo, giấy thời bao cấp nhuốm màu thời gian',
    summary: "Tiểu thuyết đặc sắc của nhà văn Nhật Tuấn ra đời trong giai đoạn văn học khởi sắc đầu thời kỳ Đổi Mới. Tác phẩm đào sâu vào những góc khuất tâm lý, sự xung đột giữa khát vọng hạnh phúc cá nhân và những định kiến khắt khe của xã hội, miêu tả thứ 'ngọn lửa lạnh' âm ỉ thiêu đốt tâm hồn con người trước ngã rẽ cuộc đời.",
    quote: 'Có những ngọn lửa không bùng cháy rực rỡ mà âm ỉ lạnh giá, thiêu đốt tâm can con người giữa những giằng xé của số phận.',
    cover_image_url: '/book-lua-lanh.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 23,
    qr_code: 'BSNM-023',
    title: 'Cái Đầm Ma (La Mare au Diable)',
    author: 'Giorgio Xăng (George Sand)',
    publish_year: 1985,
    publisher: 'NXB Văn Học',
    category: 'Văn Học Kinh Điển Pháp',
    price: 35000,
    condition_note: 'Ấn bản NXB Văn Học, bìa giấy mộc màu nâu đất in minh họa chân dung hình học thanh lịch, sờn góc gáy nguyên bản, ruột sách sạch đẹp',
    summary: 'Kiệt tác tiểu thuyết đồng quê tiêu biểu nhất của nữ văn hào Pháp George Sand (Amantine Lucile Dupin). Tác phẩm mở ra bức tranh thiên nhiên tuyệt mỹ và câu chuyện tình yêu mộc mạc, thuần khiết giữa chàng nông dân Germain góa vợ và cô gái Marie nghèo khó bên chiếc đầm lầy ma quái, ca ngợi phẩm giá cao đẹp của những con người lao động lương thiện.',
    quote: 'Tình yêu chân chính không bao giờ cần đến sự giả dối hay tính toán; nó tỏa sáng giản dị như giọt sương mai trên cỏ nội đồng quê.',
    cover_image_url: '/book-cai-dam-ma.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 24,
    qr_code: 'BSNM-024',
    title: 'Đất Lành Nơi Người Lính Trở Về',
    author: 'Nhiều Tác Giả (Mai Linh Corporation tuyển chọn)',
    publish_year: 2005,
    publisher: 'NXB Thanh Niên',
    category: 'Ký Sự & Tri Ân Người Lính',
    price: 35000,
    condition_note: 'Bìa màu xanh lá biểu trưng hy vọng và hòa bình, hình ảnh nụ cười rạng rỡ của người lính và thế hệ trẻ, ruột in sạch đẹp, gáy chắc chắn',
    summary: "Tập ký sự và hồi ức xúc động do NXB Thanh Niên phối hợp phát hành, tôn vinh những người lính Cụ Hồ sau ngày đất nước hòa bình trở về với đời thường. Dù mang trên mình thương tật và ký ức chiến tranh khốc liệt, họ vẫn tiếp tục cống hiến trên mặt trận lao động xây dựng đất nước, gắn liền với tinh thần tri ân thương binh - bệnh binh sâu sắc của dự án Bìa Sờn Nắng Mới.",
    quote: 'Đất nước thanh bình là mảnh đất lành che chở cho những người lính trở về, nơi những vết thương chiến tranh được xoa dịu bằng tình thương và sự tri ân.',
    cover_image_url: '/book-dat-lanh-noi-nguoi-linh-tro-ve.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 25,
    qr_code: 'BSNM-025',
    title: 'Một Cõi Nhân Gian Bé Tí',
    author: 'Nguyễn Khải',
    publish_year: 1989,
    publisher: 'NXB Mũi Cà Mau',
    category: 'Tiểu Thuyết Chiêm Nghiệm & Đổi Mới',
    price: 35000,
    condition_note: 'Ấn bản nguyên bản năm 1989 của NXB Mũi Cà Mau (logo MCM), bìa tranh sơn dầu hoang hoải thời gian sờn mép phong trần, ruột nguyên vẹn',
    summary: "Một trong những tiểu thuyết chiêm nghiệm xuất sắc của nhà văn Nguyễn Khải (Giải thưởng Hồ Chí Minh) viết sau khi chuyển vào sinh sống tại miền Nam thời Đổi Mới. Bằng giọng văn điềm đạm, hóm hỉnh và sắc sảo, tác giả soi chiếu vào số phận những con người bình thường trong 'một cõi nhân gian bé tí' để tự vấn và đúc kết những quy luật sâu sắc về nhân tình thế thái.",
    quote: 'Cuộc đời dẫu chỉ là một cõi nhân gian bé tí, nhưng trong cõi ấy chứa đựng tất cả hỷ nộ ái ố và phẩm giá không thể trộn lẫn của con người.',
    cover_image_url: '/book-mot-coi-nhan-gian-be-ti.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 26,
    qr_code: 'BSNM-026',
    title: 'Mai Phục Trong Đêm Hè',
    author: 'Hồ Anh Thái',
    publish_year: 1989,
    publisher: 'NXB Kim Đồng',
    category: 'Truyện Dài & Tuổi Trẻ Đổi Mới',
    price: 35000,
    condition_note: 'Ấn bản nguyên gốc năm 1989 của NXB Kim Đồng (logo chú mèo mộc mạc), bìa tranh sơn dầu đêm hè huyền bí pha sắc cam rực lửa, sờn góc gáy thời bao cấp',
    summary: 'Truyện dài xuất sắc thời kỳ đầu cầm bút của nhà văn Hồ Anh Thái – một trong những cây bút tiên phong hàng đầu của văn học Việt Nam đương đại thời kỳ Đổi Mới. Tác phẩm kể về những chuyến phiêu lưu, trăn trở và nhiệt huyết tuổi trẻ của thế hệ thanh niên trong một mùa hè đầy thử thách và bí ẩn, qua ngòi bút sắc sảo, mới mẻ và giàu chất thơ.',
    quote: 'Đêm hè không chỉ có sự tĩnh lặng của bóng tối, mà còn ẩn chứa những ngọn lửa âm ỉ của khát vọng và những cuộc mai phục số phận.',
    cover_image_url: '/book-mai-phuc-trong-dem-he.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 27,
    qr_code: 'BSNM-027',
    title: 'Lê Vĩnh Hòa — Tuyển Tập',
    author: 'Lê Vĩnh Hòa (Đoàn Thế Hối)',
    publish_year: 1986,
    publisher: 'NXB Tổng Hợp Hậu Giang & NXB Văn Nghệ TP.HCM',
    category: 'Văn Học Kháng Chiến Nam Bộ',
    price: 35000,
    condition_note: 'Ấn bản năm 1986 phối hợp giữa NXB Tổng Hợp Hậu Giang và Văn Nghệ TP.HCM, bìa hoa văn gấm cổ kính màu vàng đất, dán gáy bảo quản nguyên vẹn',
    summary: 'Tuyển tập công phu tập hợp trọn vẹn các truyện ngắn, ký sự, tùy bút và thơ của nhà văn liệt sĩ Lê Vĩnh Hòa (Đoàn Thế Hối, 1932–1967) – người được truy tặng Giải thưởng Nhà nước về Văn học Nghệ thuật. Tác phẩm phản ánh chân thực, xúc động khí phách bất khuất và tình cảm nồng hậu của quân dân miền Tây Nam Bộ trong kháng chiến chống Mỹ.',
    quote: 'Mỗi trang viết của người cầm bút - chiến sĩ là một tấc đất quê hương được gìn giữ bằng máu và tình yêu thương vô bờ bến.',
    cover_image_url: '/book-le-vinh-hoa-tuyen-tap.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 28,
    qr_code: 'BSNM-028',
    title: 'Truyện Cổ Dân Gian Lào',
    author: 'Nhiều Tác Giả (Văn Tiến Đào dịch & tuyển chọn)',
    publish_year: 1986,
    publisher: 'NXB Kim Đồng',
    category: 'Truyện Cổ Tích & Văn Hóa Dân Gian',
    price: 25000,
    condition_note: 'Thuộc Tủ Sách Truyện Cổ Dân Gian NXB Kim Đồng, bìa vàng rực rỡ minh họa nàng Kinari/tiên nữ cánh chim huyền ảo, giấy bãi bằng ngả màu cổ tích',
    summary: 'Tập hợp những câu chuyện cổ tích và thần thoại dân gian đặc sắc nhất của xứ sở Triệu Voi (Lào) được NXB Kim Đồng ấn hành cho thiếu nhi Việt Nam. Cuốn sách mở ra thế giới thần tiên mầu nhiệm về tình bạn, lòng nhân ái, sự thủy chung và tình đoàn kết gắn bó keo sơn giữa hai dân tộc anh em Việt - Lào.',
    quote: 'Truyện cổ tích là dòng suối mát lành nuôi dưỡng tâm hồn trẻ thơ về cái thiện, lòng nhân ái và ước mơ công bằng.',
    cover_image_url: '/book-truyen-co-dan-gian-lao.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 29,
    qr_code: 'BSNM-029',
    title: 'Con Hổ Vùng Sangrila (Der Tiger von Shangri-La)',
    author: 'Ha-ry Tuyr-kơ (Harry Thürk)',
    publish_year: 1984,
    publisher: 'NXB Thuận Hóa',
    category: 'Tiểu Thuyết Phiêu Lưu & Tình Báo',
    price: 35000,
    condition_note: 'Ấn bản tiếng Việt năm 1984 của NXB Thuận Hóa, bìa tranh vẽ người đàn ông kiên nghị bên tòa bảo tháp phương Đông huyền bí, sờn mép phong trần',
    summary: "Tiểu thuyết trinh thám phiêu lưu ly kỳ của nhà văn nổi tiếng người Đức Harry Thürk (nguyên tác 'Der Tiger von Shangri-La'). Bối cảnh trải dài nơi vùng núi non hiểm trở Sangrila bí ẩn ở Nam Á, theo chân cuộc đối đầu căng thẳng giữa những điệp viên quốc tế và các thế lực ngầm nhằm bảo vệ bí mật sống còn.",
    quote: 'Nơi đỉnh non cao mù sương, bản lĩnh và lòng quả cảm của con người mới là thứ vũ khí lợi hại nhất trước mọi hiểm nguy rình rập.',
    cover_image_url: '/book-con-ho-vung-sangrila.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 30,
    qr_code: 'BSNM-030',
    title: 'Mao — Tấn Thảm Kịch Của Đảng Cộng Sản Trung Quốc (Tập III)',
    author: 'Viện Mác - Lênin Liên Xô (Ban Biên tập biên dịch)',
    publish_year: 1985,
    publisher: 'NXB Thông Tin Lý Luận',
    category: 'Lịch Sử & Tư Liệu Chính Trị',
    price: 35000,
    condition_note: 'Ấn bản Tập III năm 1985 của NXB Thông Tin Lý Luận, bìa giấy mộc màu nâu đất in typo chữ lớn nguyên bản, mép gáy sờn nhẹ, ruột sách nguyên vẹn',
    summary: 'Tập III trong công trình nghiên cứu và khảo cứu lịch sử chính trị đồ sộ do NXB Thông Tin Lý Luận ấn hành vào giữa thập niên 1980. Cuốn sách cung cấp góc nhìn tư liệu lịch sử quan trọng về các biến động nội bộ phức tạp, đường lối và những giai đoạn thăng trầm của lịch sử phong trào cộng sản quốc tế giai đoạn cận hiện đại.',
    quote: 'Nhìn thẳng vào những thảm kịch và bài học của lịch sử là con đường duy nhất để xây dựng một tương lai chân chính và tiến bộ.',
    cover_image_url: '/book-mao-tan-tham-kich.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 31,
    qr_code: 'BSNM-031',
    title: 'Gương Mặt Cuộc Đời',
    author: 'Hoàng Lại Giang',
    publish_year: 1987,
    publisher: 'NXB Mũi Cà Mau & NXB Văn Nghệ TP.HCM',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản nguyên gốc năm 1987 của NXB Mũi Cà Mau (logo MCM), bìa typo chữ khối đen viền đỏ ấn tượng, sờn mép phong trần, ruột nguyên vẹn',
    summary: 'Cuốn tiểu thuyết xã hội giàu tính hiện thực và gai góc của nhà văn Hoàng Lại Giang. Tác phẩm phản ánh chân thực những va đập dữ dội trong đời sống xã hội thời kỳ chuyển giao kinh tế, khắc họa diện mạo đa chiều của con người trước danh lợi, sự tha hóa và những cuộc đấu tranh nội tâm để giữ vẹn nhân cách lương thiện.',
    quote: 'Gương mặt cuộc đời dẫu có muôn vàn góc cạnh khốc liệt, phẩm giá và sự tử tế vẫn là tấm gương sáng nhất soi rọi lòng người.',
    cover_image_url: '/book-guong-mat-cuoc-doi.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 32,
    qr_code: 'BSNM-032',
    title: 'Cú Móc Vào Tim',
    author: 'Nôen Vécxin (Noël Vexin)',
    publish_year: 1984,
    publisher: 'NXB Thể Dục Thể Thao',
    category: 'Tiểu Thuyết Tình Báo & Thể Thao',
    price: 35000,
    condition_note: 'Ấn bản năm 1984 của NXB Thể Dục Thể Thao, bìa tranh vẽ người phụ nữ bí ẩn bên Khải Hoàn Môn và võ sĩ quyền Anh, sờn mép giấy bãi bằng vàng đều',
    summary: 'Tiểu thuyết trinh thám tình báo thể thao độc đáo và hiếm có của nhà văn Pháp Noël Vexin do Phan La Sơn & Phan Thanh Đẩu dịch. Lấy bối cảnh sàn đấu quyền Anh chuyên nghiệp quốc tế tại Paris, tác phẩm mở ra cuộc điều tra nghẹt thở về những âm mưu cá cược ngầm, rửa tiền và mạng lưới tình báo cài cắm đằng sau những đòn knock-out sinh tử.',
    quote: 'Trên sàn đấu cũng như trong cuộc đời, cú đòn nguy hiểm nhất không nhắm vào thể xác mà nhắm thẳng vào lòng tin và trái tim con người.',
    cover_image_url: '/book-cu-moc-vao-tim.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 33,
    qr_code: 'BSNM-033',
    title: 'Mao — Tấn Thảm Kịch Của Đảng Cộng Sản Trung Quốc (Tập IV)',
    author: 'Viện Mác - Lênin Liên Xô (Ban Biên tập biên dịch)',
    publish_year: 1985,
    publisher: 'NXB Thông Tin Lý Luận',
    category: 'Lịch Sử & Tư Liệu Chính Trị',
    price: 35000,
    condition_note: 'Ấn bản Tập IV nguyên gốc năm 1985 của NXB Thông Tin Lý Luận, bìa giấy mộc màu nâu đất in typo tiêu đề cổ kính, sờn mép thời gian',
    summary: "Tập IV tiếp nối bộ khảo cứu chính trị tư liệu quan trọng do NXB Thông Tin Lý Luận xuất bản giữa thập niên 80. Cuốn sách tập trung phân tích những bước ngoặt đầy kịch tính, phong trào 'Đại nhảy vọt' và 'Cách mạng Văn hóa', cung cấp tư liệu lịch sử phong phú về bài học xây dựng đường lối phát triển xã hội chủ nghĩa.",
    quote: 'Lịch sử luôn công bằng trong việc phán xét những sai lầm và vinh quang, để nhân loại tìm thấy con đường phát triển đúng đắn hơn.',
    cover_image_url: '/book-mao-tan-tham-kich-tap-iv.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 34,
    qr_code: 'BSNM-034',
    title: 'Bông Hồng Cho Emily (A Rose for Emily)',
    author: 'William Faulkner & Nhiều Tác Giả (Nobel 1949)',
    publish_year: 1985,
    publisher: 'NXB Tác Phẩm Mới (TPM)',
    category: 'Truyện Ngắn Thế Giới Chọn Lọc',
    price: 35000,
    condition_note: 'Thuộc bộ Truyện Ngắn Thế Giới Chọn Lọc (Tập II) của NXB Tác Phẩm Mới (TPM), bìa tranh vẽ chân dung người thiếu nữ huyền bí với gam màu hoài cổ, gáy sờn mộc mạc',
    summary: "Tuyển tập truyện ngắn kinh điển thế giới do NXB Tác Phẩm Mới tuyển chọn, nổi bật với kiệt tác 'Bông hồng cho Emily' của đại văn hào Mỹ William Faulkner (Giải Nobel Văn học 1949). Tác phẩm đi sâu vào bi kịch tinh thần, sự cô đơn cùng cực và sự suy tàn của tầng lớp quý tộc miền Nam nước Mỹ qua phong cách Gothic kinh điển.",
    quote: 'Thời gian trôi qua chầm chậm như một bóng ma, và bông hồng của ký ức vĩnh viễn nằm lại trong căn phòng cô quạnh của số phận.',
    cover_image_url: '/book-bong-hong-cho-emily.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 35,
    qr_code: 'BSNM-035',
    title: 'Hiệp Hai',
    author: 'A. Ta-ra-đan-kin & I. Phê-xen-cô (Liên Xô)',
    publish_year: 1983,
    publisher: 'NXB Lao Động',
    category: 'Tiểu Thuyết Phản Gián & Trinh Thám Xô Viết',
    price: 35000,
    condition_note: 'Ấn bản năm 1983 của NXB Lao Động (Côi Thịnh & An Thư dịch), bìa tranh vẽ hai mảng màu đỏ cam - đen phong cách phản gián Liên Xô, sờn mép thời bao cấp',
    summary: "Tiểu thuyết trinh thám phản gián Xô Viết kinh điển của hai tác giả Taradankin và Fesenko. Tác phẩm tái hiện cuộc đấu trí âm thầm nhưng quyết liệt của lực lượng an ninh Liên Xô trong việc lần theo các manh mối gián điệp tinh vi thời Chiến tranh Lạnh, bảo vệ an ninh và bí mật quốc gia trong 'hiệp đấu' tiếp nối đầy cam go.",
    quote: 'Trong cuộc đấu trí thầm lặng bảo vệ bình yên cho đất nước, người chiến sĩ an ninh không được phép lơ là dù chỉ một tích tắc.',
    cover_image_url: '/book-hiep-hai.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 36,
    qr_code: 'BSNM-036',
    title: 'Những Cuộc Phiêu Lưu Của Sơ-lốc Hôm (Tập III)',
    author: 'Arthur Conan Doyle',
    publish_year: 1987,
    publisher: 'Sở Văn Hóa & Thông Tin Lâm Đồng',
    category: 'Trinh Thám Kinh Điển',
    price: 35000,
    condition_note: 'Ấn bản Tập III năm 1987 của Sở VH&TT Lâm Đồng do Phạm Quang Trung dịch, giấy bãi bằng vàng nâu đậm chất thời bao cấp, có lưu bút/chữ ký kỷ niệm ngày 12/6/87, ruột vẹn nguyên',
    summary: 'Tập III trong bộ truyện trinh thám kinh điển thế giới về thám tử đại tài Sherlock Holmes và bác sĩ Watson, do dịch giả Phạm Quang Trung chuyển ngữ và Sở VH&TT Lâm Đồng xuất bản năm 1987. Tác phẩm tập hợp những vụ kỳ án hóc búa bậc nhất với phương pháp suy luận quy nạp sắc bén, đưa độc giả bước vào không khí London sương mù cuối thế kỷ 19.',
    quote: 'Khi bạn đã loại trừ những điều không thể, thì điều còn lại, dù khó tin đến đâu, vẫn phải là sự thật.',
    cover_image_url: '/book-nhung-cuoc-phieu-luu-cua-so-loc-hom-tap-3.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 37,
    qr_code: 'BSNM-037',
    title: 'Nơi Đối Mặt',
    author: 'Nguyễn Ngọc Mộc',
    publish_year: 1982,
    publisher: 'NXB Quân Đội Nhân Dân',
    category: 'Truyện & Ký Quân Đội',
    price: 35000,
    condition_note: 'Ấn bản nguyên gốc năm 1982 của NXB Quân Đội Nhân Dân (logo QĐND), bìa màu vàng đất với phong cách đồ họa ước lệ độc đáo, mép sờn thời gian, trang giấy nhuốm màu ký ức chiến trận',
    summary: 'Tập truyện giàu xúc cảm của nhà văn Quân đội Nguyễn Ngọc Mộc, do NXB Quân Đội Nhân Dân ấn hành năm 1982. Tác phẩm tái hiện những khoảnh khắc đối mặt gay cấn và thử thách cam go của người lính nơi tiền tuyến — không chỉ là đối mặt với hiểm nguy bom đạn, mà còn là đối mặt với chính phẩm giá, lý tưởng và tình đồng đội cao cả.',
    quote: 'Nơi đối mặt gay gắt nhất giữa sự sống và cái chết cũng chính là nơi phẩm chất người lính ngời sáng vẻ đẹp kiên trung và nhân ái.',
    cover_image_url: '/book-noi-doi-mat.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 38,
    qr_code: 'BSNM-038',
    title: 'Con Hổ Vùng Sangrila',
    author: 'Harry Thürk (Ha-ry Tuyr-kơ)',
    publish_year: 1970,
    publisher: 'NXB Văn Hóa (bản dịch tiếng Việt)',
    category: 'Tiểu Thuyết Phiêu Lưu & Chính Trị',
    price: 35000,
    condition_note: 'Bản in tiếng Việt thời bao cấp, bìa tranh vẽ xanh lục phong cách khắc gỗ — chân dung người đàn ông cùng ngôi đền Á Đông bí ẩn, giấy bãi bằng vàng nâu, mép sờn phong trần, ruột nguyên vẹn',
    summary: 'Tiểu thuyết phiêu lưu chính trị đầy kịch tính của nhà văn Đức Harry Thürk (1927–2005), xuất bản lần đầu năm 1970. Lấy bối cảnh vùng núi non huyền bí Shangri-La ở Trung Á, tác phẩm theo chân nhân vật chính xâm nhập vào lãnh địa hoang dã nơi những thế lực ngầm đang thao túng, hé mở cuộc đấu trí sinh tử giữa các mạng lưới tình báo quốc tế thời Chiến tranh Lạnh.',
    quote: 'Trong vùng đất huyền thoại ấy, ranh giới giữa thiên đường và địa ngục mỏng manh như sợi tóc, và con hổ chính là kẻ cai quản luật chơi.',
    cover_image_url: '/book-con-ho-vung-sangrila.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 39,
    qr_code: 'BSNM-039',
    title: 'Aivanhô (Ivanhoe) — Tập I',
    author: 'Walter Scott (Oantơ Scốt)',
    publish_year: 1988,
    publisher: 'NXB Văn Học, Hà Nội',
    category: 'Tiểu Thuyết Lịch Sử Kinh Điển',
    price: 35000,
    condition_note: 'Thuộc tủ sách Văn Học Cổ Điển Nước Ngoài — Văn Học Anh, bản in lần thứ hai do Trần Kiêm dịch và giới thiệu, bìa giấy mộc màu nâu đất in typo tinh giản, sờn mép cổ kính, ruột nguyên vẹn',
    summary: "Tập I trong bộ tiểu thuyết lịch sử kinh điển 'Ivanhoe' của đại văn hào Scotland Walter Scott, do dịch giả Trần Kiêm chuyển ngữ công phu và NXB Văn Học ấn hành. Lấy bối cảnh nước Anh thế kỷ XII thời vua Richard Sư Tử Tâm đi Thập tự chinh, tác phẩm kể về cuộc phiêu lưu của hiệp sĩ Wilfred xứ Ivanhoe giữa cuộc xung đột giữa người Saxon bản địa và người Norman, đan xen tình yêu, danh dự và âm mưu tranh ngôi của Hoàng tử John.",
    quote: 'Vinh quang thực sự của hiệp sĩ không nằm ở lưỡi kiếm sắc bén mà ở trái tim can đảm dám đứng lên bảo vệ công lý và kẻ yếu thế.',
    cover_image_url: '/book-aivanho.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 40,
    qr_code: 'BSNM-040',
    title: 'Trò Chơi',
    author: 'Iuri Bônđarép (Yuri Bondarev)',
    publish_year: 1986,
    publisher: 'Hội Văn Nghệ Nghĩa Bình',
    category: 'Tiểu Thuyết Xã Hội Xô Viết',
    price: 35000,
    condition_note: 'Ấn bản năm 1986 của Hội Văn Nghệ Nghĩa Bình, bản dịch Lê Khánh Trường, bìa giấy mộc nâu vàng giản dị đặc trưng xuất bản địa phương thời bao cấp, sờn mép thời gian',
    summary: "Tiểu thuyết xã hội gây tranh cãi của nhà văn Xô Viết lừng danh Yuri Bondarev (1924–2020), xuất bản năm 1985 — đúng giai đoạn Liên Xô bước vào thời kỳ cải tổ Perestroika. Khác với phong cách chiến tranh quen thuộc, Bondarev chuyển hướng khắc họa đời sống tầng lớp trí thức thượng lưu Moscow — đạo diễn, họa sĩ, viện sĩ — qua đó phơi bày những 'trò chơi' quyền lực, danh vọng và sự tha hóa đạo đức đang âm thầm gặm nhấm nền tảng xã hội.",
    quote: 'Cuộc đời là một trò chơi mà kẻ thua cuộc đáng thương nhất là người đánh mất chính mình giữa những ván cờ danh lợi.',
    cover_image_url: '/book-tro-choi.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 41,
    qr_code: 'BSNM-041',
    title: 'Tự Do Hay Là Chết — Tập I',
    author: 'Nikos Kazantzakis (Nikôx Kazanzaki)',
    publish_year: 1985,
    publisher: 'NXB Văn Học, Hà Nội',
    category: 'Tiểu Thuyết Lịch Sử Hy Lạp',
    price: 35000,
    condition_note: 'Thuộc tủ sách Văn Học Hiện Đại Nước Ngoài — Văn Học Hy Lạp, bản dịch Hoàng Nguyên Kỳ, bìa giấy mộc nâu đất in typo nghiêm cẩn, sờn mép cổ kính',
    summary: "Tập I trong bộ tiểu thuyết lịch sử hùng tráng 'Freedom or Death' (tên gốc: Captain Michalis) của đại văn hào Hy Lạp Nikos Kazantzakis, do Hoàng Nguyên Kỳ dịch. Lấy bối cảnh cuộc khởi nghĩa năm 1889 của nhân dân đảo Crete chống ách thống trị Ottoman, tác phẩm xoay quanh thủ lĩnh Đội trưởng Michalis — con người kiên cường thề không cạo râu, không mặc trang phục nào ngoài màu đen cho đến ngày Crete giải phóng.",
    quote: 'Tự do hay là chết — không có con đường thứ ba cho những ai đã chọn sống với phẩm giá và lý tưởng.',
    cover_image_url: '/book-tu-do-hay-la-chet.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 42,
    qr_code: 'BSNM-042',
    title: 'Ngày Cuối Của Cuộc Chiến Tranh',
    author: 'Lam Giang',
    publish_year: 1986,
    publisher: 'NXB Văn Nghệ Thành Phố Hồ Chí Minh',
    category: 'Truyện Chiến Tranh Cách Mạng',
    price: 35000,
    condition_note: 'Ấn bản nguyên gốc năm 1986 của NXB Văn Nghệ TP.HCM, bìa giấy mộc nâu vàng in typo giản dị, sờn mép và bìa bọc nhựa thủ công kỷ niệm, ruột nguyên vẹn',
    summary: 'Tập truyện chiến tranh cách mạng của nhà văn Lam Giang, do NXB Văn Nghệ TP.HCM ấn hành năm 1986. Tác phẩm tái hiện những ngày tháng cuối cùng trước giải phóng — khoảnh khắc sinh tử đầy bi tráng của người lính và nhân dân nơi tuyến lửa, nơi hy vọng hòa bình và nỗi đau mất mát đan xen trong từng trang giấy thấm đẫm nghĩa tình đồng đội.',
    quote: 'Ngày cuối cùng của cuộc chiến tranh không phải là ngày hết đau thương, mà là ngày bắt đầu của những ký ức không bao giờ lãng quên.',
    cover_image_url: '/book-ngay-cuoi-cua-cuoc-chien-tranh.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 43,
    qr_code: 'BSNM-043',
    title: 'Yôxta Becling (Gösta Berlings Saga)',
    author: 'Selma Lagerlöf (Nobel 1909)',
    publish_year: 1986,
    publisher: 'NXB Văn Học & Sở VH-TT Nghĩa Bình',
    category: 'Tiểu Thuyết Kinh Điển Thụy Điển',
    price: 35000,
    condition_note: "Bản dịch Hoàng Thiếu Sơn, bìa giấy mộc nâu vàng với logo 'vh' đặc trưng NXB Văn Học, tiêu đề chữ nghệ thuật viền xanh vàng nổi bật, hai sọc đỏ trang trí, sờn mép cổ kính thời bao cấp",
    summary: 'Tiểu thuyết đầu tay kinh điển của nữ văn hào Thụy Điển Selma Lagerlöf — người phụ nữ đầu tiên trên thế giới đoạt giải Nobel Văn học (1909). Lấy bối cảnh vùng Värmland tuyết phủ những năm 1820, tác phẩm kể về Gösta Berling — một mục sư bị cách chức vì thói nghiện rượu, được bà chủ trang trại Ekeby cứu sống, rồi dấn thân vào những cuộc phiêu lưu đầy huyền thoại xen lẫn cảnh sắc thiên nhiên Bắc Âu thơ mộng và truyền thuyết dân gian kỳ bí.',
    quote: 'Cuộc đời là một bữa tiệc lớn nơi mỗi linh hồn lạc lối đều có thể tìm lại ánh sáng cứu rỗi giữa tuyết trắng và ngọn lửa ấm áp của tình người.',
    cover_image_url: '/book-yoxta-becling.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 44,
    qr_code: 'BSNM-044',
    title: 'Huế Mùa Xuân',
    author: 'Thanh Hải (Phạm Bá Ngoãn)',
    publish_year: 1970,
    publisher: 'NXB Văn Nghệ Giải Phóng',
    category: 'Thơ Kháng Chiến',
    price: 30000,
    condition_note: 'Ấn bản Tập 1 năm 1970 của NXB Văn Nghệ Giải Phóng (logo VNRP), bìa tranh vẽ cờ giải phóng trên nền Kinh thành Huế, giấy bãi bằng vàng nâu nhuốm thời gian, sờn mép phong trần — ấn phẩm thời chiến hiếm có',
    summary: 'Tập thơ kháng chiến đầy xúc cảm của nhà thơ Thanh Hải (1930–1980) — một trong những cây bút tiên phong đặt nền móng cho nền văn học cách mạng miền Nam. Được NXB Văn Nghệ Giải Phóng ấn hành giữa thời kỳ kháng chiến chống Mỹ, tập thơ thấm đẫm tình yêu quê hương Huế, hình tượng Bác Hồ và khát vọng hòa bình thống nhất non sông. Thanh Hải chính là tác giả bài thơ bất hủ "Mùa Xuân Nho Nhỏ" trong chương trình giáo dục phổ thông.',
    quote: 'Một mùa xuân nho nhỏ, lặng lẽ dâng cho đời — dù là tuổi hai mươi, dù là khi tóc bạc.',
    cover_image_url: '/book-hue-mua-xuan.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 45,
    qr_code: 'BSNM-045',
    title: 'Kể Chuyện Ăn Cốm Giữa Sân',
    author: 'Nguyễn Khắc Phục',
    publish_year: 1980,
    publisher: 'NXB Văn Học',
    category: 'Trường Ca & Thơ',
    price: 30000,
    condition_note: 'Ấn bản giấy mộc nâu đất thời bao cấp, bìa không có tranh minh họa chỉ in typo giản dị, có chữ ký tay "Ngọc Trân" và số "38" bút chì — dấu ấn lưu truyền qua nhiều đời chủ nhân, mép sờn phong trần',
    summary: 'Trường ca đậm chất sử thi của nhà văn, nhà thơ Nguyễn Khắc Phục (1947–2016) — người nổi tiếng với khối lượng tác phẩm đồ sộ về chiến tranh và đời sống hậu chiến. "Kể Chuyện Ăn Cốm Giữa Sân" là tác phẩm thơ dài hơi tái hiện không khí thanh bình của đời sống làng quê Việt Nam thời hậu chiến, nơi những câu chuyện giản dị bên sân nhà ăn cốm mùa thu chứa đựng cả một bề dày ký ức chiến tranh và khát vọng hồi sinh.',
    quote: 'Ăn cốm giữa sân chiều thu, nghe tiếng dế kêu mà nhớ về bao đồng đội đã nằm lại nơi chiến trường xa.',
    cover_image_url: '/book-ke-chuyen-an-com-giua-san.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 46,
    qr_code: 'BSNM-046',
    title: 'Đứng Trước Biển',
    author: 'Nguyễn Mạnh Tuấn',
    publish_year: 1982,
    publisher: 'NXB Văn Nghệ Thành Phố Hồ Chí Minh',
    category: 'Tiểu Thuyết Xã Hội Hiện Thực',
    price: 35000,
    condition_note: 'Ấn bản lần đầu năm 1982 của NXB Văn Nghệ TP.HCM, bìa chữ viết tay nghệ thuật xanh lục — đỏ nổi bật trên nền giấy mộc, sờn mép phong trần, ruột nguyên vẹn — cuốn sách từng gây tranh cãi lớn trong giới văn nghệ',
    summary: 'Tiểu thuyết xã hội hiện thực gây chấn động văn đàn Việt Nam đầu thập niên 80 của nhà văn Nguyễn Mạnh Tuấn. Lấy bối cảnh xí nghiệp đánh cá vùng biển miền Nam sau ngày thống nhất, tác phẩm trực diện phơi bày sự cứng nhắc của cơ chế quản lý bao cấp, những va chạm gay gắt giữa cái cũ và cái mới, giữa lý tưởng và thực tế. Cùng với "Những khoảng cách còn lại" và "Cù lao tràm", đây là bộ ba tiểu thuyết làm nên tên tuổi Nguyễn Mạnh Tuấn — người tiên phong dùng văn chương phản ánh chân thực hiện thực đời sống trước thời kỳ Đổi Mới.',
    quote: 'Đứng trước biển cả mênh mông, con người nhỏ bé nhất vẫn có thể chọn hướng đi đúng nếu dám nhìn thẳng vào sự thật.',
    cover_image_url: '/book-dung-truoc-bien.jpg',
    status: 'AVAILABLE'
  },
  {
    id: 47,
    qr_code: 'BSNM-047',
    title: 'Những Tiếng Nổ Rung Chuyển Saigon',
    author: 'Lam Giang & Nguyệt Bình',
    publish_year: 1984,
    publisher: 'NXB Thành Phố Hồ Chí Minh',
    category: 'Truyện Ký Lịch Sử & Biệt Động',
    price: 35000,
    condition_note: 'Ấn bản năm 1984 của NXB TP.HCM, bìa giấy mộc nâu vàng in typo đậm chữ khối, có dấu mộc đỏ thư viện/đơn vị kỷ niệm, sờn mép thời gian — ấn phẩm tư liệu chiến tranh quý giá',
    summary: 'Truyện ký lịch sử bi hùng của hai tác giả Lam Giang và Nguyệt Bình, do NXB TP.HCM ấn hành năm 1984. Tác phẩm tái hiện chân thực các trận đánh kinh hoàng và chiến công phi thường của lực lượng Biệt động Sài Gòn trong cuộc kháng chiến chống Mỹ — những tiếng nổ làm rung chuyển cả thành phố và khiến quân thù khiếp sợ, đồng thời tôn vinh sự hy sinh thầm lặng của những chiến sĩ biệt động anh hùng.',
    quote: 'Những tiếng nổ ấy không chỉ rung chuyển Sài Gòn mà còn vang vọng mãi trong lịch sử dân tộc như lời thề bất khuất của người lính biệt động.',
    cover_image_url: '/book-nhung-tieng-no-rung-chuyen-saigon.jpg',
    status: 'AVAILABLE'
  }
];

export const INITIAL_GUESTBOOK: GuestbookEntry[] = [];
